6.0.99-1

diff --git a/add-vstsdk-location-var.patch b/add-vstsdk-location-var.patch
--- a/add-vstsdk-location-var.patch
+++ b/add-vstsdk-location-var.patch
@@ -1,62 +1,41 @@
-From 12a8bd02d330bb5fe54857af38271b4ae6fc8cae Mon Sep 17 00:00:00 2001
-From: Teteros <Teteros@users.noreply.github.com>
-Date: Wed, 22 Apr 2020 05:12:26 +0100
-Subject: [PATCH] Build: Add RADIUM_VST2SDK_PATH environment variable
-
-Adds an extra search path users can use to help locate their VST2 SDK.
-Simply export RADIUM_VST2SDK_PATH in before make packages when desired.
-
-Also fixes the link in the check_dependencies.sh since Steinberg
-deprecated VST2 so it was no longer available in the mentioned link.
----
- Makefile.Qt                      | 2 +-
- check_dependencies.sh            | 9 +++++----
- pluginhost/Builds/Linux/Makefile | 2 +-
- 3 files changed, 7 insertions(+), 6 deletions(-)
-
-diff --git a/Makefile.Qt b/Makefile.Qt
-index bd2bd8161..4e2c8928b 100755
---- a/Makefile.Qt
-+++ b/Makefile.Qt
-@@ -297,7 +297,7 @@ MENU_TYPE = -DUSE_QT_MENU=1 -DUSE_GTK_MENU=0
+diff -aur --no-dereference '--exclude=.git' radium-6.0.99.old/Makefile.Qt radium-6.0.99.new/Makefile.Qt
+--- radium-6.0.99.old/Makefile.Qt	2020-09-01 14:37:08.000000000 +0100
++++ radium-6.0.99.new/Makefile.Qt	2020-09-01 20:10:33.357697286 +0100
+@@ -306,7 +306,7 @@
  
  FLAGOPTS = $(DEFINES) -DGUIISQT -DFULL_VERSION=$(FULL_VERSION) -DIS_LITTLE_ENDIAN=1 -DUSE_OPENGL=1 $(VISUAL) $(REQTYPE_TYPE) $(MENU_TYPE)
  
--COMMONOPT = -c $(RADIUM_BFD_CFLAGS) `cat buildtype.opt` -I$(GCDIR)/include -I$(P) -I$(PYPATH) `cat flagopts.opt` $(MIDIINC) $(OS_OPTS) $(VST_OPTS) -I${HOME}/boost_1_70_0 -I${HOME}/boost_1_67_0 -I${HOME}/boost_1_63_0 -I ~/SDKs/VST_SDK/VST2_SDK/ -I ~/SDKs/vstsdk2.4/ -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unknown-pragmas -fno-strict-aliasing -Wmissing-field-initializers -Wnull-dereference 
-+COMMONOPT = -c $(RADIUM_BFD_CFLAGS) `cat buildtype.opt` -I$(GCDIR)/include -I$(P) -I$(PYPATH) `cat flagopts.opt` $(MIDIINC) $(OS_OPTS) $(VST_OPTS) -I${HOME}/boost_1_70_0 -I${HOME}/boost_1_67_0 -I${HOME}/boost_1_63_0 -I${RADIUM_VST2SDK_PATH} -I ~/SDKs/VST_SDK/VST2_SDK/ -I ~/SDKs/vstsdk2.4/ -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unknown-pragmas -fno-strict-aliasing -Wmissing-field-initializers -Wnull-dereference 
+-COMMONOPT = -c `cat buildtype.opt` -I$(GCDIR)/include -I$(P) -I$(PYPATH) `cat flagopts.opt` $(MIDIINC) $(OS_OPTS) $(VST_OPTS) -I${HOME}/boost_1_70_0 -I${HOME}/boost_1_67_0 -I${HOME}/boost_1_63_0 -I ~/SDKs/VST_SDK/VST2_SDK/ -I ~/SDKs/vstsdk2.4/ -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unknown-pragmas -fno-strict-aliasing -Wmissing-field-initializers -Wnull-dereference 
++COMMONOPT = -c `cat buildtype.opt` -I$(GCDIR)/include -I$(P) -I$(PYPATH) `cat flagopts.opt` $(MIDIINC) $(OS_OPTS) $(VST_OPTS) -I${HOME}/boost_1_70_0 -I${HOME}/boost_1_67_0 -I${HOME}/boost_1_63_0 -I${RADIUM_VST2SDK_PATH} -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unknown-pragmas -fno-strict-aliasing -Wmissing-field-initializers -Wnull-dereference 
  #-fdelete-null-pointer-checks 
  # -Werror
  
-diff --git a/check_dependencies.sh b/check_dependencies.sh
-index 1e13a5136..4cc11517b 100755
---- a/check_dependencies.sh
-+++ b/check_dependencies.sh
-@@ -225,10 +225,11 @@ if ! pkg-config --cflags glib-2.0 >/dev/null 2>/dev/null ; then
-     echo "glib-2.0 not found"
-     exit 5
- fi
--
--if [[ ! -f ~/SDKs/vstsdk2.4/pluginterfaces/vst2.x/aeffect.h && ! -f ~/SDKs/"VST3 SDK"/pluginterfaces/vst2.x/aeffect.h && ! -f ~/SDKs/VST_SDK/VST2_SDK/pluginterfaces/vst2.x/aeffect.h ]] ; then
--    echo 'Steinberg VST headers not found. (Missing "~/SDKs/vstsdk2.4/pluginterfaces/vst2.x/aeffect.h or "~/SDKs/VST3 SDK/pluginterfaces/vst2.x/aeffect.h" or "~/SDKs/VST_SDK/VST2_SDK/pluginterfaces/vst2.x/aeffect.h")'
--    echo 'You should find these files in the "VST Audio Plug-Ins SDK" from http://www.steinberg.net/en/company/developers.html . Unless Steinberg have changed the directory structure again, it should enough to unzip the file into your ~/SDKs directory.'
-+if [[ ! -f "${RADIUM_VST2SDK_PATH}/pluginterfaces/vst2.x/aeffect.h" && ! -f ~/SDKs/vstsdk2.4/pluginterfaces/vst2.x/aeffect.h && ! -f ~/SDKs/"VST3 SDK"/pluginterfaces/vst2.x/aeffect.h && ! -f ~/SDKs/VST_SDK/VST2_SDK/pluginterfaces/vst2.x/aeffect.h ]] ; then
-+    echo 'Steinberg VST2 headers not found. (Missing "~/SDKs/vstsdk2.4/pluginterfaces/vst2.x/aeffect.h or "~/SDKs/VST3 SDK/pluginterfaces/vst2.x/aeffect.h" or "~/SDKs/VST_SDK/VST2_SDK/pluginterfaces/vst2.x/aeffect.h")'
-+    echo 'You may obtain a copy of the VST2 SDK from here: https://www.steinberg.net/sdk_downloads/vstsdk367_03_03_2017_build_352.zip'
-+    echo 'It should enough to unzip the file into your ~/SDKs directory.'
-+    echo 'Alternatively pass the RADIUM_VST2SDK_PATH environment variable during build which has the above headers to specify another search path.'
+diff -aur --no-dereference '--exclude=.git' radium-6.0.99.old/check_dependencies.sh radium-6.0.99.new/check_dependencies.sh
+--- radium-6.0.99.old/check_dependencies.sh	2020-09-01 14:37:08.000000000 +0100
++++ radium-6.0.99.new/check_dependencies.sh	2020-09-01 20:12:11.634639063 +0100
+@@ -226,13 +226,6 @@
      exit 5
  fi
  
-diff --git a/pluginhost/Builds/Linux/Makefile b/pluginhost/Builds/Linux/Makefile
-index ff10bea46..b58ee51f6 100644
---- a/pluginhost/Builds/Linux/Makefile
-+++ b/pluginhost/Builds/Linux/Makefile
-@@ -8,7 +8,7 @@ ifndef CONFIG
+-if [[ ! -f ~/SDKs/vstsdk2.4/pluginterfaces/vst2.x/aeffect.h && ! -f ~/SDKs/"VST3 SDK"/pluginterfaces/vst2.x/aeffect.h && ! -f ~/SDKs/VST_SDK/VST2_SDK/pluginterfaces/vst2.x/aeffect.h ]] ; then
+-    echo 'Steinberg VST headers not found. (Missing "~/SDKs/vstsdk2.4/pluginterfaces/vst2.x/aeffect.h or "~/SDKs/VST3 SDK/pluginterfaces/vst2.x/aeffect.h" or "~/SDKs/VST_SDK/VST2_SDK/pluginterfaces/vst2.x/aeffect.h")'
+-    echo 'You should find these files in the "VST Audio Plug-Ins SDK" from http://www.steinberg.net/en/company/developers.html . Unless Steinberg has changed the directory structure again, it should enough to unzip the file into your ~/SDKs directory.'
+-    exit 5
+-fi
+-
+-
+ if [[ $4 == "test_build" ]] ; then
+     if [ `uname` == "Linux" ] ; then
+         if [ ! -f bin/packages/deletemetorebuild ] ; then
+diff -aur --no-dereference '--exclude=.git' radium-6.0.99.old/pluginhost/Builds/Linux/Makefile radium-6.0.99.new/pluginhost/Builds/Linux/Makefile
+--- radium-6.0.99.old/pluginhost/Builds/Linux/Makefile	2020-09-01 14:37:08.000000000 +0100
++++ radium-6.0.99.new/pluginhost/Builds/Linux/Makefile	2020-09-01 20:18:12.189005049 +0100
+@@ -8,7 +8,7 @@
    CONFIG=Debug
  endif
  
 -COMMONCPPFLAGS := $(DEPFLAGS) -D "LINUX=1" -D "_DEBUG=1" -D "JUCE_CHECK_MEMORY_LEAKS=0" -D "JUCER_LINUX_MAKE_7346DA2A=1" -D "JUCE_APP_VERSION=1.0.0" -D "JUCE_APP_VERSION_HEX=0x10000" -I /usr/include -I /usr/include/freetype2 -I~/SDKs/VST_SDK/VST3_SDK -I ~/SDKs/VST_SDK/VST2_SDK/ -I ~/SDKs/VST3\ SDK -I ../../JuceLibraryCode -I ../../JuceLibraryCode/modules -I ~/SDKs/vstsdk2.4 -DJUCE_APP_CONFIG_HEADER="\"AppConfig.h\"" -mfpmath=sse -msse2
-+COMMONCPPFLAGS := $(DEPFLAGS) -D "LINUX=1" -D "_DEBUG=1" -D "JUCE_CHECK_MEMORY_LEAKS=0" -D "JUCER_LINUX_MAKE_7346DA2A=1" -D "JUCE_APP_VERSION=1.0.0" -D "JUCE_APP_VERSION_HEX=0x10000" -I /usr/include -I /usr/include/freetype2 -I$(RADIUM_VST2SDK_PATH) -I~/SDKs/VST_SDK/VST3_SDK -I ~/SDKs/VST_SDK/VST2_SDK/ -I ~/SDKs/VST3\ SDK -I ../../JuceLibraryCode -I ../../JuceLibraryCode/modules -I ~/SDKs/vstsdk2.4 -DJUCE_APP_CONFIG_HEADER="\"AppConfig.h\"" -mfpmath=sse -msse2
++COMMONCPPFLAGS := $(DEPFLAGS) -D "LINUX=1" -D "_DEBUG=1" -D "JUCE_CHECK_MEMORY_LEAKS=0" -D "JUCER_LINUX_MAKE_7346DA2A=1" -D "JUCE_APP_VERSION=1.0.0" -D "JUCE_APP_VERSION_HEX=0x10000" -I /usr/include -I /usr/include/freetype2 -I$(RADIUM_VST2SDK_PATH) -I ../../JuceLibraryCode -I ../../JuceLibraryCode/modules -DJUCE_APP_CONFIG_HEADER="\"AppConfig.h\"" -mfpmath=sse -msse2
  
  ifeq (,$(findstring clang,$(CXX)))
  	COMMONCPPFLAGS += -Wno-class-memaccess 
