Added timeouts to curl calls, added info about subdeps.
Signed-off-by: mvtab <mvtabilitas@protonmail.com>

diff --git a/aurx b/aurx
--- a/aurx
+++ b/aurx
@@ -261,6 +261,9 @@ print_error() {
 		73 )
 			echo "[-] Could not touch required file \"${REQUIRED_FILE}\"."
 			;;
+		74 )
+			echo "[-] Could not establish a connection to the AUR HTTP."
+			;;
 		* )
 			echo "[-] No error message found for error ${GIVEN_ERROR}."
 			;;
@@ -363,7 +366,7 @@ compare_versions() {
 			;;
 		rpc )
 			local LATEST_VERSION
-			LATEST_VERSION=$(curl \
+			LATEST_VERSION=$(curl --connect-timeout 60 --max-time 180 \
 				"https://aur.archlinux.org/rpc/v5/info?arg[]=${TARGET_PACKAGE}" 2> /dev/null \
 				| jq -r .results.[0].Version)
 			;;
@@ -491,7 +494,7 @@ aur_rpc_search() {
 		REQUESTS+=("-o${TMP_PATH?TMP_PATH not defined.}/temp_request_${TARGET_KEYWORD}")
 	done
 
-	curl --parallel --parallel-immediate --parallel-max "${PARALLEL}" \
+	curl --connect-timeout 60 --max-time 180 --parallel --parallel-immediate --parallel-max "${PARALLEL}" \
 		"${REQUESTS[@]}" 2> /dev/null
 
 	for TARGET_KEYWORD in ${TARGET_KEYWORDS}; do
@@ -569,7 +572,8 @@ aur_rpc_suggest() {
 		REQUESTS+=( "https://aur.archlinux.org/rpc/v5/suggest/${TARGET_KEYWORD}" )
 	done
 
-	RESULTS=$(curl --parallel --parallel-immediate --parallel-max "${PARALLEL}" "${REQUESTS[@]}" 2> /dev/null)
+	RESULTS=$(curl --connect-timeout 5 --max-time 15 --parallel --parallel-immediate \
+		--parallel-max "${PARALLEL}" "${REQUESTS[@]}" 2> /dev/null)
 	RESULTS=$(
 		for RESULT in ${RESULTS}; do
 			echo "${RESULT}" | jq -r ".[:${SEARCH_RESULTS}] | .[]" 2> /dev/null
@@ -981,6 +985,11 @@ fi
 if [[ -z "${TARGET_PACKAGES}" ]]; then
 	print_error 56
 	exit 56
+fi
+
+# Check for internet connection.
+if ! curl --connect-timeout 10 "https://aur.archlinux.org/rpc/v5/info" 2> /dev/null 1>&2; then
+	print_error 74
 fi
 
 # Execution.
