Added curl-opts opt.
Signed-off-by: mvtab <mvtabilitas@protonmail.com>

diff --git a/aurx b/aurx
--- a/aurx
+++ b/aurx
@@ -17,14 +17,14 @@
 
 
 # Metadata.
-INTERNAL_VERSION="1.0.3-2"
+INTERNAL_VERSION="1.0.3-3"
 POSSIBLE_OPERATIONS=("install" "remove" "update" "search" "completion" "list" "suggest" "version")
 GENERAL_OPTIONS=("-a" "--all" "-f" "--force" "-h" "--help" "-p" "--persistent-path" "-t" "--tmp-path" "-v" "--verbosity")
 INSTALL_OPTIONS=("-c" "--cleanup" "-C" "--clean-operation" "-d" "--download-only" "-x" "--comparison-criteria" "-g" "--git-opts" "-M" "--makepkg-opts" "-V" "-W" "--overwrite-existing" "-w" "-s" "--source-path" "--verify-versions" "--wipe-existing")
 REMOVE_OPTIONS=("-R" "--remove-opts")
-UPDATE_OPTIONS=("-k" "--keep-sources" "-K" "--keep-failed-sources" "-B" "--block-overwrite" "-x" "--comparison-criteria" "-M" "--makepkg-opts")
-SEARCH_OPTIONS=("-r" "--search-results" "-S" "--search-criteria" "-b" "--sort-by" "-o" "--order-by" "-z" "--output" "-O" "--no-out-of-date" "-m" "--maintained" "-i" "--no-mark-installed" "-u" "--no-mark-update" "-P" "--parallel")
-SUGGEST_OPTIONS=("-r" "--search-results" "-o" "--order-by" "-z" "--output")
+UPDATE_OPTIONS=("-B" "--block-overwrite" "-x" "--comparison-criteria" "-k" "--keep-sources" "-K" "--keep-failed-sources" "-l" "--curl-opts" "-M" "--makepkg-opts")
+SEARCH_OPTIONS=("-l" "--curl-opts" "-m" "--maintained" "-O" "--no-out-of-date" "-i" "--no-mark-installed" "-u" "--no-mark-update" "-P" "--parallel" "-r" "--search-results" "-S" "--search-criteria" "-b" "--sort-by" "-o" "--order-by" "-z" "--output")
+SUGGEST_OPTIONS=("-l" "--curl-opts" "-r" "--search-results" "-o" "--order-by" "-z" "--output")
 COMPLETION_OPTIONS=("-e" "--executable-name")
 LIST_OPTIONS=("-u" "--no-mark-update" "-P" "--parallel" "-i" "--no-mark-installed")
 AVAILABLE_COMPLETIONS=("bash")
@@ -67,6 +67,14 @@ PERSISTENT_PATH="${AURX_PERSISTENT_PATH:-${HOME?HOME not defined.}/.aurx/cfg}"
 SOURCE_PATH="${AURX_SOURCE_PATH:-${HOME?HOME not defined.}/.aurx/src}"
 
 # Arrays.
+declare -a CURL_OPTS
+if [[ -n "${AURX_CURL_OPTS}" ]]; then
+	for OPT in ${AURX_CURL_OPTS}; do
+		CURL_OPTS+=("${OPT}")
+	done
+else
+	CURL_OPTS=()
+fi
 declare -a GIT_OPTS
 if [[ -n "${AURX_GIT_OPTS}" ]]; then
 	for OPT in ${AURX_GIT_OPTS}; do
@@ -126,6 +134,7 @@ usage() {
 		  -x, --comparison-criteria [CRITERIA]  criteria to use when comparing packages. ("rpc")
 		                                        "rpc" - AUR HTTP RPC API, "makepkg" - filesystem.
 		  -d, --download-only                   download the source from AUR and stop.
+		  -g, --git-opts [OPTS]..               opts to give in to git operations. ("")
 		  -M, --makepkg-opts [OPTS]..           opts to give in to makepkg installs. ("-sirc")
 		  -W, --overwrite-existing              overwrite eventually existing sources.
 		  -s, --source-path [PATH]              work directory for builds.("\${HOME}/.aurx/src")
@@ -136,6 +145,8 @@ usage() {
 		  -R, --remove-opts [OPTS]..            opts to give in to pacman for removing package. ("-R")
 
 		  search:
+		  -l, --curl-opts                       opts to give in to curl.
+		                                        timeouts can be overwritten with this.
 		  -m, --maintained                      filter out unmaintained packages.
 		  -i, --no-mark-installed               don't show the '[installed]' mark.
 		  -u, --no-mark-update                  do not check for updates while searching.
@@ -156,6 +167,8 @@ usage() {
 		                                        "votes", "popularity".
 
 		  suggest:
+		  -l, --curl-opts                       opts to give in to curl.
+		                                        timeouts can be overwritten with this.
 		  -o, --order-by [ORDER]                how to order search results. ("descending")
 		                                        "ascending", "descending".
 		  -r, --search-results [COUNT]          number of results to suggest, max 20. (20)
@@ -210,7 +223,7 @@ print_error() {
 			echo "[!] Could not remove \"${SELECTED_PACKAGE}\" from the package_list."
 			;;
 		30 )
-			echo "[!] Could not gather AUR HTTP data. Connection successful."
+			echo "[!] Could not gather AUR HTTP data."
 			;;
 		31 )
 			echo "[!] Could not filter AUR HTTP responses."
@@ -555,7 +568,7 @@ compare_versions() {
 			;;
 		rpc )
 			local LATEST_VERSION
-			if ! LATEST_VERSION=$(curl --connect-timeout 60 --max-time 180 \
+			if ! LATEST_VERSION=$(curl --connect-timeout 60 --max-time 180 "${CURL_OPTS[@]}" \
 				"https://aur.archlinux.org/rpc/v5/info?arg[]=${TARGET_PACKAGE}" 2> /dev/null \
 				| jq -r .results.[0].Version); then
 				print_error 74
@@ -678,7 +691,7 @@ write_package_list() {
 aur_rpc_suggest() {
 	local TARGET_KEYWORD="${1}"
 
-	if ! RESULTS=$(curl --connect-timeout 5 --max-time 10 \
+	if ! RESULTS=$(curl --connect-timeout 5 --max-time 10 "${CURL_OPTS[@]}" \
 		"https://aur.archlinux.org/rpc/v5/suggest/${TARGET_KEYWORD}" 2> /dev/null); then
 		print_error 74
 		exit 74
@@ -720,7 +733,7 @@ gather_aur_data() {
 	done
 
 	if ! curl --connect-timeout 60 --max-time 180 --parallel --parallel-immediate --parallel-max "${PARALLEL}" \
-		"${REQUESTS[@]}" 2> /dev/null; then
+		"${CURL_OPTS[@]}" "${REQUESTS[@]}" 2> /dev/null; then
 		print_error 74
 		exit 74
 	fi
@@ -904,10 +917,10 @@ fi
 # Options.
 LONGOPTS=''
 LONGOPTS+='all,block-overwrite,cleanup,clean-operation,download-only,force,help,keep-sources,keep-failed-sources,maintained,no-mark-installed,no-mark-update,no-out-of-date,overwrite-existing,verify-versions,wipe-existing'
-LONGOPTS+=',comparison-criteria:,executable-name:,git-opts:,makepkg-opts:,output:,order-by:,parallel:,persistent-path:,remove-opts:,search-criteria:,search-results:,sort-by:,source-path:,tmp-path:,verbosity:'
+LONGOPTS+=',comparison-criteria:,curl-opts:,executable-name:,git-opts:,makepkg-opts:,output:,order-by:,parallel:,persistent-path:,remove-opts:,search-criteria:,search-results:,sort-by:,source-path:,tmp-path:,verbosity:'
 OPTIONS=''
 OPTIONS+='aBcCdfhkKmiOuVwW'
-OPTIONS+='b:e:g:M:o:p:P:r:R:s:S:t:v:x:z:'
+OPTIONS+='b:e:g:l:M:o:p:P:r:R:s:S:t:v:x:z:'
 if ! PARSED_OPTIONS=$(getopt --options="${OPTIONS}" --longoptions="${LONGOPTS}" --name "${0}" -- "${@}"); then
 	print_error 51
 	exit 51
@@ -936,6 +949,13 @@ while true; do
 		-C|--clean-operation )
 			CLEAN_OPERATION=true
 			shift
+			;;
+		-l|--curl-opts )
+			CURL_OPTS=()
+			for OPT in ${2}; do
+				CURL_OPTS+=("${OPT}")
+			done
+			shift 2
 			;;
 		-d|--download-only )
 			DOWNLOAD_ONLY=true
