1.0.6-4: Added config opt, tidied up README, improved config description in usage..

diff --git a/aurx b/aurx
--- a/aurx
+++ b/aurx
@@ -38,6 +38,10 @@ usage() {
 		Options:
 		  general:
 		  -a --all                             add all installed packages to the operation.
+		  -c --config [JSON_STRING]            JSON configuration for aurx.
+		                                       same options as explicit, but capitalized and with
+		                                       underscores instead of hyphens, e.g. TMP_PATH.
+		                                       It has the highest priority and beautified JSON works too.
 		  -f --force                           forces the operation, where appliable.
 		  -h --help                            display this information and exit.
 		     --persistent-path [PATH]          path for persistent data. ("\${HOME}/.aurx/cfg")
@@ -232,8 +236,8 @@ print_error() {
 			;;
 		76 )
 			local TEMP_PACKAGES
-			TEMP_PACKAGES="${PACKAGES_NOT_FOUND[@]}"
-			echo "[!] Could not find ${TEMP_PACKAGES[*]/\ /,\ }." >&2
+			TEMP_PACKAGES="$(echo ${PACKAGES_NOT_FOUND[*]})"
+			echo "[!] Could not find ${TEMP_PACKAGES}." >&2
 			;;
 		77 )
 			echo "[!] The suggest operation can not output json." >&2
@@ -583,10 +587,10 @@ load_explicit_opts() {
 
 	LONGOPTS=''
 	LONGOPTS+='all,block-overwrite,cleanup,clean-operation,download-only,force,help,keep-sources,keep-failed-sources,maintained,no-mark-installed,no-mark-update,no-out-of-date,overwrite-existing,verify-versions,version,wipe-existing'
-	LONGOPTS+=',comparison-criteria:,curl-opts:,executable-name:,git-opts:,makepkg-opts:,output:,order-by:,parallel:,persistent-path:,remove-opts:,search-criteria:,search-results:,sort-by:,source-path:,tmp-path:,verbosity:'
+	LONGOPTS+=',comparison-criteria:,config:,curl-opts:,executable-name:,git-opts:,makepkg-opts:,output:,order-by:,parallel:,persistent-path:,remove-opts:,search-criteria:,search-results:,sort-by:,source-path:,tmp-path:,verbosity:'
 	OPTIONS=''
 	OPTIONS+='adfhvV'
-	OPTIONS+='e:G:C:M:o:p:R:t:x:'
+	OPTIONS+='e:G:c:C:M:o:p:R:t:x:'
 	if ! PARSED_OPTIONS=$(getopt --options="${OPTIONS}" --longoptions="${LONGOPTS}" --name "${0}" -- "${@}"); then
 		print_error 51
 		exit 51
@@ -614,6 +618,10 @@ load_explicit_opts() {
 				;;
 			-x|--comparison-criteria )
 				COMPARISON_CRITERIA="${2}"
+				shift 2
+				;;
+			-c|--config )
+				GIVEN_CONFIG_STRING="${2}"
 				shift 2
 				;;
 			-C|--curl-opts )
@@ -1219,6 +1227,7 @@ execute_script() {
 	load_env_vars
 	load_explicit_opts "${@}"
 	load_piped_packages
+	[[ -n "${GIVEN_CONFIG_STRING}" ]] && load_config "${GIVEN_CONFIG_STRING}"
 	launch_sanity_checks
 	launch_system_checks
 	process_pseudofunctions
@@ -1239,15 +1248,15 @@ METADATA_ARRAYS=("INTERNAL_VARIABLES" "INTERNAL_ARRAYS" "POSSIBLE_OPERATIONS" "G
 declare "${METADATA_VARIABLES[@]}"
 declare -a "${METADATA_ARRAYS[@]}"
 
-INTERNAL_VERSION="1.0.6-2"
+INTERNAL_VERSION="1.0.6-4"
 INTERNAL_VARIABLES=("ALL" "BLOCK_OVERWRITE" "CLEAN_OPERATION" "CLEANUP" "COMPARISON_CRITERIA" \
-	"DOWNLOAD_ONLY" "EXECUTABLE_NAME" "FORCE" "KEEP_FAILED_SOURCES" "KEEP_SOURCES" "MAINTAINED" \
-	"NO_MARK_INSTALLED" "NO_MARK_UPDATE" "NO_OUT_OF_DATE" "ORDER_BY" "OUTPUT" "OVERWRITE_EXISTING" \
+	"DOWNLOAD_ONLY" "EXECUTABLE_NAME" "FORCE" "GIVEN_CONFIG_STRING" "KEEP_FAILED_SOURCES" "KEEP_SOURCES" \
+	"MAINTAINED" "NO_MARK_INSTALLED" "NO_MARK_UPDATE" "NO_OUT_OF_DATE" "ORDER_BY" "OUTPUT" "OVERWRITE_EXISTING" \
 	"PARALLEL" "PERSISTENT_PATH" "SEARCH_CRITERIA" "SEARCH_RESULTS" "SORT_BY" "SOURCE_PATH" "TMP_PATH" \
 	"VERBOSITY" "VERIFY_VERSIONS" "WIPE_EXISTING")
 INTERNAL_ARRAYS=("CURL_OPTS" "GIT_OPTS" "MAKEPKG_OPTS" "REMOVE_OPTS")
 POSSIBLE_OPERATIONS=("install" "remove" "update" "search" "completion" "list" "suggest")
-GENERAL_OPTIONS=("-a" "--all" "-f" "--force" "-h" "--help" "--persistent-path" "-t" "--tmp-path" "--verbosity" "-v" "--version")
+GENERAL_OPTIONS=("-a" "--all" "-c" "--config" "-f" "--force" "-h" "--help" "--persistent-path" "-t" "--tmp-path" "--verbosity" "-v" "--version")
 INSTALL_OPTIONS=("--cleanup" "--clean-operation" "-x" "--comparison-criteria" "-d" "--download-only" "-G" \
 	"--git-opts" "-M" "--makepkg-opts" "--overwrite-existing" "--source-path" "-V" "--verify-versions" "--wipe-existing")
 REMOVE_OPTIONS=("-R" "--remove-opts")
