Update

diff --git a/blurry-text-fix.install b/blurry-text-fix.install
--- a/blurry-text-fix.install
+++ b/blurry-text-fix.install
@@ -1,10 +1,36 @@
+pre_install() {
+	if [[ ! -f "/usr/share/gtk-4.0/settings.ini" ]]
+	then
+		echo "### ERROR: /usr/share/gtk-4.0/settings.ini doesn't exist."
+		exit 1
+	fi
+}
+
 post_install() {
-	mv /usr/share/gtk-4.0/settings.ini /usr/share/gtk-4.0/settings-old.ini
+	if [[ ! -f "/usr/share/gtk-4.0/settings-old.ini" ]]
+	then
+		echo "Renaming settings.ini to settings-old.ini."
+		mv /usr/share/gtk-4.0/settings.ini /usr/share/gtk-4.0/settings-old.ini
+	fi
+
+	echo "Installing modified config to settings.ini."
 	mv /usr/share/gtk-4.0/settings-modified.ini /usr/share/gtk-4.0/settings.ini
-	flatpak override --filesystem=xdg-config/gtk-4.0
+
+	if [[ -f "/usr/bin/flatpak" ]]
+	then
+		echo "Flatpak found! Overriding flatpak.."
+		flatpak override --filesystem=xdg-config/gtk-4.0
+	fi
+
+	echo "### Done. Please relog to apply changes."
+}
+
+post_upgrade() {
+	post_install
 }
 
 post_remove() {
 	rm /usr/share/gtk-4.0/settings.ini
 	mv /usr/share/gtk-4.0/settings-old.ini /usr/share/gtk-4.0/settings.ini
+	echo "### Done. Please relog to apply changes."
 }
