update relocs, fix bolt, update readme

diff --git a/buildcache.sh.in b/buildcache.sh.in
--- a/buildcache.sh.in
+++ b/buildcache.sh.in
@@ -11,10 +11,10 @@ source "$LIBRARY/util/option.sh"
 executable_functions+=('executable_buildcache')
 
 executable_buildcache() {
-	if check_buildoption "buildcache" "y"; then
-		if ! type -p buildcache >/dev/null; then
-			error "$(gettext "Cannot find the %s binary required for compiler cache usage.")" "buildcache"
-			return 1
-		fi
-	fi
+    if check_buildoption "buildcache" "y"; then
+        if ! type -p buildcache >/dev/null; then
+            error "$(gettext "Cannot find the %s binary required for compiler cache usage.")" "buildcache"
+            return 1
+        fi
+    fi
 }
diff --git a/optipng-exec.sh.in b/optipng-exec.sh.in
--- a/optipng-exec.sh.in
+++ b/optipng-exec.sh.in
@@ -13,10 +13,10 @@ source "$LIBRARY/util/option.sh"
 executable_functions+=('executable_optipng')
 
 executable_optipng() {
-  if check_option "optipng" "y"; then
-    if ! type -p optipng >/dev/null; then
-      error "$(gettext "Cannot find the %s binary required for optimizing PNG image files.")" "optipng"
-      ret=1
+    if check_option "optipng" "y"; then
+        if ! type -p optipng >/dev/null; then
+            error "$(gettext "Cannot find the %s binary required for optimizing PNG image files.")" "optipng"
+            ret=1
+        fi
     fi
-  fi
 }
diff --git a/svgo-exec.sh.in b/svgo-exec.sh.in
--- a/svgo-exec.sh.in
+++ b/svgo-exec.sh.in
@@ -13,10 +13,10 @@ source "$LIBRARY/util/option.sh"
 executable_functions+=('executable_svgo')
 
 executable_svgo() {
-  if check_option "svgo" "y"; then
-    if ! type -p svgo >/dev/null; then
-      error "$(gettext "Cannot find the %s binary required for optimizing SVG image files.")" "svgo"
-      ret=1
+    if check_option "svgo" "y"; then
+        if ! type -p svgo >/dev/null; then
+            error "$(gettext "Cannot find the %s binary required for optimizing SVG image files.")" "svgo"
+            ret=1
+        fi
     fi
-  fi
 }
diff --git a/upx-exec.sh.in b/upx-exec.sh.in
--- a/upx-exec.sh.in
+++ b/upx-exec.sh.in
@@ -13,10 +13,10 @@ source "$LIBRARY/util/option.sh"
 executable_functions+=('executable_upx')
 
 executable_upx() {
-  if check_option "upx" "y"; then
-    if ! type -p upx >/dev/null; then
-      error "$(gettext "Cannot find the %s binary required for compressing binaries.")" "upx"
-      ret=1
+    if check_option "upx" "y"; then
+        if ! type -p upx >/dev/null; then
+            error "$(gettext "Cannot find the %s binary required for compressing binaries.")" "upx"
+            ret=1
+        fi
     fi
-  fi
 }
