Add symbolic links to Monotype fonts.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,5 +1,31 @@
 #!/bin/bash
+# Ilya Kuzmin; Russia, Saint-Petersbugr, 2019. ©
+# Generate DejaVu font descriptions to enable it in groff.
+
 output=font
+
+function register_font
+{
+    local base_name="$1"; shift;
+    local font_name="$1"; shift;
+
+    echo $font_name
+
+    local internalname=`awk '/^internalname/{print $2;}' $font_name`
+
+
+    if ! grep "\b$internalname\t" "$output/devpdf/download" &>/dev/null; then
+        echo -e "\t$internalname\t../$base_name.pfa" >> $output/devpdf/download
+    else
+        echo "Font with name '$internalname' already present in '$output/devpdf/download'"
+    fi
+
+    if ! grep "\b$internalname\t" $output/devps/download &>/dev/null; then
+       echo -e "\t$internalname\t../$base_name.pfa" >> $output/devps/download
+    else
+        echo "Font with name '$internalname' already present in '$output/devps/download'"
+    fi
+}
 
 ttf=$(find /usr/share/fonts/TTF/ -name "DejaVu*")
 if  [ -z "$ttf" ]; then
@@ -64,28 +90,26 @@ for name in $ttf; do
         font_name=${font_name/DejaVuMathTeXGyre/DeVuTex}
     fi
 
-    echo $font_name
 
     if ! afmtodit $output/$base_name.afm $textmap $font_name 2>/dev/null; then
-        echo "Can't generate groff font descritpion for $base_name"
+        echo "Can't generate groff font description '$font_name' for '$base_name'"
         echo -1
     fi
 
-    internalname=`awk '/^internalname/{print $2;}' $font_name`
+    register_font $base_name $font_name
 
-    if ! grep "\b$internalname\t" "$output/devpdf/download" &>/dev/null; then
-        echo -e "\t$internalname\t../$base_name.pfa" >> $output/devpdf/download
-    else
-        echo "Font with name '$internalname' already present in '$output/devpdf/download'"
-    fi
-
-    if ! grep "\b$internalname\t" $output/devps/download &>/dev/null; then
-       echo -e "\t$internalname\t../$base_name.pfa" >> $output/devps/download
-    else
-        echo "Font with name '$internalname' already present in '$output/devps/download'"
-    fi
-
-    rm $output/$base_name.afm
     cp $font_name $output/devps/
-    mv $font_name $output/devpdf/
+    cp $font_name $output/devpdf/
+
+    if [[ "$font_name" == "DeVuSaMoR" ]]; then
+        for dev in devps devpdf; do
+            echo "Link $font_name -> $dev/DeVuSeMo, $dev/DeVuSaMo" 
+            cd $output/$dev;
+            ln -s DeVuSaMoR DeVuSaMo
+            ln -s DeVuSaMoR DeVuSeMo
+            cd - >/dev/null;
+        done
+    fi
+
+    rm $output/$base_name.afm $font_name
 done
