Fixing crashes.

diff --git a/clonehero b/clonehero
--- a/clonehero
+++ b/clonehero
@@ -14,20 +14,12 @@ if ! cd "$dir"; then
 	exit 1
 fi
 
-# Executable *must* be in a writable directory.
-# The game is probably trying to write to files relative to the executable's
-# path rather than the working directory.
-# This way a link does not work, as the game seemingly dereferences it and tries
-# to write inside /opt/clonehero.
-if ! cp /opt/clonehero/clonehero clonehero; then
-	echo "Failed to copy 'clonehero' to '$dir/clonehero'"
-	exit 1
-fi
-
-# And then we link everything else we can avoid copying.
-for f in UnityPlayer.so clonehero_Data; do
-	if ! ln -sfT "/opt/clonehero/$f" "$f"; then
-		echo "Failed to link '$f' to '$dir/$f'"
+# We have to copy the required files to get the game to run in a local user
+# directory. Symbolic linking leads to runtime errors, running with a different
+# working directory than the binary doesn't work either.
+for f in clonehero_Data clonehero UnityPlayer.so; do
+	if ! cp -rf "/opt/clonehero/$f" "$dir/$f"; then
+		echo "Failed to copy '$f' to '$dir/$f'"
 		exit 1
 	fi
 done
