Did a lot of reorganization

diff --git a/cozy-standalone.install b/cozy-standalone.install
--- a/cozy-standalone.install
+++ b/cozy-standalone.install
@@ -3,12 +3,8 @@
 # Maintainer: Brendan Abolivier <brendan@cozycloud.cc>
 
 # Fancy message is fancy
-msg_blue() {
+msg() {
     printf "${blue}==>${bold} $1${all_off}\n"
-}
-
-prompt_blue() {
-    printf "${blue}==>${bold} $1${all_off}"
 }
 
 all_off="$(tput sgr0)"
@@ -16,220 +12,199 @@ bold="${all_off}$(tput bold)"
 blue="${bold}$(tput setaf 4)"
 
 post_install() {
-	npm install -g coffee-script
-	[ ! -d /usr/share/cozy ] && mkdir /usr/share/cozy
-	msg_blue "Downloading config file for Cozy Indexer"
-	curl https://raw.githubusercontent.com/cozy/cozy-debian/master/supervisor-cozy-indexer > /usr/share/cozy/supervisor-cozy-indexer
-	msg_blue "Downloading config file for Cozy Controller"
-	curl https://raw.githubusercontent.com/cozy/cozy-debian/master/supervisor-cozy-controller > /usr/share/cozy/supervisor-cozy-controller
+    msg "Checking ports availability"
+    msg "9002"
+    lsof -i :9002 > /dev/null 2>&1
+    if [ $? = "0" ]; then
+        msg "Port 9002 (used by the Cozy controller) is already in use on this machine."
+        exit 1
+    fi
+    msg "9101"
+    lsof -i :9101 > /dev/null 2>&1
+    if [ $? = "0" ]; then
+        msg "Port 9101 (used by the Cozy Data System) is already in use on this machine."
+        exit 1
+    fi
+    msg "9103"
+    lsof -i :9103 > /dev/null 2>&1
+    if [ $? = "0" ]; then
+        msg "Port 9103 (used by the Cozy Home) is already in use on this machine."
+        exit 1
+    fi
+    msg "9104"
+    lsof -i :9104 > /dev/null 2>&1
+    if [ $? = "0" ]; then
+        msg "Port 9104 (used by the Cozy authentication proxy) is already in use on this machine."
+        exit 1
+    fi
 
-	COZY_DOMAIN=
-	msg_blue "Choose you Cozy's FQDN (fully-qualified domain name).\nA self-signed certificate will be issued for this domain only."
-	while [ -z $COZY_DOMAIN ]; do
-		msg_blue "Domain name of your Cozy [cozy.example.tld]: " 
-		read res 
-		COZY_DOMAIN=$res
-	done
+    msg "Installing CoffeeScript"
+    npm install -g coffee-script
 
-	msg_blue "Chosen domain name for Cozy: $COZY_DOMAIN"
+    msg 'Installing NPM dependencies...'
+    npm config set python /usr/bin/python2
+    [ ! -d /usr/local/lib/node_modules/cozy-controller ] && npm install -g cozy-controller
+    [ ! -d /usr/local/lib/node_modules/cozy-monitor ] && npm install -g cozy-monitor
 
-	msg_blue 'Installing NPM dependencies...'
-	npm config set python /usr/bin/python2
-	[ ! -d /usr/local/lib/node_modules/cozy-controller ] && npm install -g cozy-controller
-	[ ! -d /usr/local/lib/node_modules/cozy-monitor ] && npm install -g cozy-monitor
+    msg 'Creating UNIX users...'
+    id cozy >/dev/null 2>&1 || useradd -M cozy
+    id cozy-data-system >/dev/null 2>&1 || useradd -M cozy-data-system
+    id cozy-home >/dev/null 2>&1 || useradd -M cozy-home
 
-	msg_blue 'Creating UNIX users...'
-	id cozy >/dev/null 2>&1 || useradd -M cozy
-	id cozy-data-system >/dev/null 2>&1 || useradd -M cozy-data-system
-	id cozy-home >/dev/null 2>&1 || useradd -M cozy-home
+    chown -hR cozy /etc/cozy
 
-	[ ! -d /etc/cozy ] && mkdir /etc/cozy
-	chown -hR cozy /etc/cozy
-	if [ ! -f /etc/cozy/couchdb.login ]; then
-		msg_blue 'Configuring CouchDB'
-		systemctl enable couchdb
-		systemctl start couchdb
-		msg_blue 'Generating CouchDB tokens...'
-		pwgen -1 > /etc/cozy/couchdb.login && \
-		pwgen -1 >> /etc/cozy/couchdb.login
-		while ! curl -s 127.0.0.1:5984 >/dev/null; do msg_blue "Waiting for CouchDB to start..."; sleep 5; done
-		curl -s -X PUT 127.0.0.1:5984/_config/admins/$(head -n1 /etc/cozy/couchdb.login) -d "\"$(tail -n1 /etc/cozy/couchdb.login)\""
-	fi
-	chown cozy-data-system /etc/cozy/couchdb.login
-	chmod 640 /etc/cozy/couchdb.login
+    if [ ! -f /etc/cozy/couchdb.login ]; then
+        msg 'Generating CouchDB tokens...'
+        pwgen -1 > /etc/cozy/couchdb.login && \
+        pwgen -1 >> /etc/cozy/couchdb.login
+        msg 'Enabling CouchDB'
+        systemctl enable couchdb
+        systemctl restart couchdb
+        COUNT=0;MAX=20
+        while ! curl -s 127.0.0.1:5984 >/dev/null; do
+            let "COUNT += 1"
+            msg "Waiting for CouchDB to start... ($COUNT/$MAX)"
+            if [[ $COUNT -ge $MAX ]]; then
+                msg "CouchDB is too long to start"
+                exit 1
+            fi
+            sleep 5
+        done
+        curl -s -X PUT 127.0.0.1:5984/_config/admins/$(head -n1 /etc/cozy/couchdb.login) -d "\"$(tail -n1 /etc/cozy/couchdb.login)\""
+    fi
+    chown cozy-data-system /etc/cozy/couchdb.login
+    chmod 640 /etc/cozy/couchdb.login
 
-	msg_blue 'Starting supervisor'
-	systemctl enable supervisord
-	systemctl start supervisord
+    msg 'Configuring Cozy Controller...'
+    CONFIGFILE=/etc/supervisor.d/cozy-controller.ini
+    if [ -f $CONFIGFILE ]; then
+        echo "Old configuration moved to /etc/supervisor.d/cozy-controller.ini.old"
+        mv /etc/supervisor.d/cozy-controller.ini /etc/supervisor.d/cozy-controller.ini.old
+    fi
+    mv /usr/share/cozy/supervisor-cozy-controller /etc/supervisor.d/cozy-controller.ini
 
-	msg_blue 'Configuring Cozy Indexer...'
-	COZY_INDEXER_DIRECTORY=/var/lib/cozy-indexer
-	if [ ! -d $COZY_INDEXER_DIRECTORY ]; then
-		msg_blue "Creating $COZY_INDEXER_DIRECTORY"
-		mkdir -p $COZY_INDEXER_DIRECTORY
-	fi
-	if [ "$(stat -c '%U:%G' $COZY_INDEXER_DIRECTORY)" != "cozy:cozy" ]; then
-		msg_blue "Fixing $COZY_INDEXER_DIRECTORY owner"
-		chown cozy:cozy $COZY_INDEXER_DIRECTORY
-	fi
+    msg 'Starting supervisor'
+    systemctl enable supervisord
+    systemctl restart supervisord
 
-	CONFIGFILE=/etc/supervisor.d/cozy-indexer.ini
-	if [ -f $CONFIGFILE ]; then
-		BEFORE=$(sha1sum $CONFIGFILE | cut -f1 -d' ')
-		EXISTING=true
-	else
-		BEFORE=
-		EXISTING=false
-	fi
+    COUNT=0;MAX=20
+    while ! curl -s 127.0.0.1:9002 >/dev/null; do
+        let "COUNT += 1"
+        msg "Waiting for Cozy Controller to start... ($COUNT/$MAX)"
+        if [[ $COUNT -ge $MAX ]]; then
+            msg "Cozy Controller is too long to start"
+            exit 1
+        fi
+        sleep 5
+    done
 
-	CONFIGFILE=/usr/share/cozy/supervisor-cozy-indexer
-	AFTER=$(sha1sum $CONFIGFILE | cut -f1 -d' ')
-	if [ "$BEFORE" != "$AFTER" ]; then
-		if $EXISTING; then
-		    echo "Your configuration file for Cozy Indexer is different from the one included in this package:"
-		    diff /etc/supervisor.d/cozy-indexer.ini /usr/share/cozy/supervisor-cozy-indexer
-		    while true; do
-		    	msg_blue "Do you want to install the new version? [Y/n]"
-		        read yn
-		        case $yn in
-		            [Nn]* ) echo "The new configuration file is stored on /usr/share/cozy/supervisor-cozy-indexer"; break;;
-		            * ) mv /etc/supervisor.d/cozy-indexer.ini /etc/supervisor.d/cozy-indexer.ini.old;
-		                cp /usr/share/cozy/supervisor-cozy-indexer /etc/supervisor.d/cozy-indexer.ini;
-		                echo "The old configuration file has been renamed as /etc/supervisor.d/cozy-indexer.ini.old"
-		                break;;
-		        esac
-		    done
-		else
-		    cp /usr/share/cozy/supervisor-cozy-indexer /etc/supervisor.d/cozy-indexer.ini
-		fi
-		supervisorctl reload
-	fi
-	while ! curl -s 127.0.0.1:9102/ >/dev/null; do msg_blue "Waiting for Cozy Indexer to start..."; sleep 5; done
+    msg 'Installing Cozy Platform apps...'
+    if [ ! -d /usr/local/cozy/apps/data-system ]; then
+        cozy-monitor install-cozy-stack
+        if [ $? = "1" ]; then echo "Error while installing the platform" && exit 1; fi
+    fi
+    cozy-monitor start data-system
+    if [ ! -d /usr/local/cozy/apps/home ]; then
+        cozy-monitor install home
+        if [ $? = "1" ]; then echo "Error while installing the platform" && exit 1; fi
+    fi
+    cozy-monitor start home
+    if [ ! -d /usr/local/cozy/apps/proxy ]; then
+        cozy-monitor install proxy
+        if [ $? = "1" ]; then echo "Error while installing the platform" && exit 1; fi
+    fi
+    cozy-monitor start proxy
 
-	msg_blue 'Configuring Cozy Controller...'
-	CONFIGFILE=/etc/supervisor.d/cozy-controller.ini
-	if [ -f $CONFIGFILE ]; then
-		BEFORE=$(sha1sum $CONFIGFILE | cut -f1 -d' ')
-		EXISTING=true
-	else
-		BEFORE=
-		EXISTING=false
-	fi
-
-	CONFIGFILE=/usr/share/cozy/supervisor-cozy-controller
-	AFTER=$(sha1sum $CONFIGFILE | cut -f1 -d' ')
-	if [ "$BEFORE" != "$AFTER" ]; then
-		if $EXISTING; then
-		    echo "Your configuration file for Cozy Controller is different from the one included in this package:"
-		    diff /etc/supervisor.d/cozy-controller.ini /usr/share/cozy/supervisor-cozy-controller
-		    while true; do
-		    	msg_blue "Do you want to install the new version? [Y/n]"
-		        read yn
-		        case $yn in
-		            [Nn]* ) echo "The new configuration file is stored on /usr/share/cozy/supervisor-cozy-controller"; break;;
-		            * ) mv /etc/supervisor.d/cozy-controller.ini /etc/supervisor.d/cozy-controller.ini.old;
-		                cp /usr/share/cozy/supervisor-cozy-controller /etc/supervisor.d/cozy-controller.ini;
-		                echo "The old configuration file has been renamed as /etc/supervisor.d/cozy-controller.ini.old"
-		                break;;
-		        esac
-		    done
-		else
-		    cp /usr/share/cozy/supervisor-cozy-controller /etc/supervisor.d/cozy-controller.ini
-		fi
-		supervisorctl reload
-	fi
-	while ! curl -s 127.0.0.1:9102 >/dev/null; do msg_blue "Waiting for Cozy Controller to start..."; sleep 5; done
-
-	msg_blue 'Installing Cozy Platform apps...'
-	if [ ! -d /usr/local/cozy/apps/data-system ]; then
-		cozy-monitor install-cozy-stack
-	fi
-	cozy-monitor start data-system
-	if [ ! -d /usr/local/cozy/apps/home ]; then
-		cozy-monitor install home
-	fi
-	cozy-monitor start home
-	if [ ! -d /usr/local/cozy/apps/proxy ]; then
-		cozy-monitor install proxy
-	fi
-	cozy-monitor start proxy
-
-	msg_blue "Downloading instance configuration script"
-	curl https://raw.githubusercontent.com/cozy/cozy-debian/master/cozy-get-instance-param.py > /usr/share/cozy/cozy-get-instance-param.py
-
-	CURRENT_DOMAIN=$(python2 /usr/share/cozy/cozy-get-instance-param.py domain)
-	if [ "$CURRENT_DOMAIN" = "$COZY_DOMAIN" ]; then
-		msg_blue "Cozy already configured with domain: $COZY_DOMAIN"
-	else
-		msg_blue "Configure Cozy with domain: $COZY_DOMAIN"
-		coffee /usr/local/cozy/apps/home/commands.coffee setdomain $COZY_DOMAIN
-	fi
-
-	CURRENT_BACKGROUND=$(python2 /usr/share/cozy/cozy-get-instance-param.py background)
+ 
+	CURRENT_BACKGROUND=`/usr/bin/cozy_management get_cozy_param background`
 	if [ "$CURRENT_BACKGROUND" != "None" ]; then
-		msg_blue "Cozy already configured with a background: $CURRENT_BACKGROUND"
+		echo "Cozy already configured with a background: $CURRENT_BACKGROUND"
 	else
-		msg_blue "Configure Cozy with default background"
+		echo "Configure Cozy with default background"
 		curl -X POST http://localhost:9103/api/instance -H "Content-Type: application/json" -d '{"background":"background-07"}'
-		echo ''
 	fi
 
-	msg_blue "Install default apps"
-	for app in calendar contacts photos emails files sync; do
-		if [ ! -f /usr/local/cozy/apps/.first-install-$app ]; then
-		    if [ -d /usr/local/cozy/apps/$app ]; then
-		        touch /usr/local/cozy/apps/.first-install-$app
-		    else
-		        cozy-monitor install $app && touch /usr/local/cozy/apps/.first-install-$app
-		    fi
-		fi
-	done
 
-	if [ ! -f /usr/local/cozy/apps/.first-install-import-from-google ]; then
-		if [ -d /usr/local/cozy/apps/import-from-google ]; then
-		    touch /usr/local/cozy/apps/.first-install-import-from-google
-		else
-		    cozy-monitor install import-from-google -r https://github.com/cozy-labs/import-from-google.git && touch /usr/local/cozy/apps/.first-install-import-from-google
-		fi
-	fi
+    msg "Installing default apps"
+    for app in calendar contacts photos emails files sync; do
+        if [ ! -f /usr/local/cozy/apps/.first-install-$app ]; then
+            if [ -d /usr/local/cozy/apps/$app ]; then
+                touch /usr/local/cozy/apps/.first-install-$app
+            else
+                cozy-monitor install $app && touch /usr/local/cozy/apps/.first-install-$app
+            fi
+        fi
+    done
 
-	msg_blue 'Generating SSL keys and certificates...'
-	if [ ! -f /etc/cozy/dh.pem ]; then
-		openssl dhparam -out /etc/cozy/dh.pem -outform PEM -2 2048
-		chmod 400 /etc/cozy/dh.pem
-	fi
-	if [ ! -f /etc/cozy/server.key ]; then
-		openssl req -x509 -nodes -newkey rsa:2048 -keyout /etc/cozy/server.key -out /etc/cozy/server.crt -days 3650 -subj "/CN=$COZY_DOMAIN"
-		chmod 400 /etc/cozy/server.key
-	fi
+    if [ ! -f /usr/local/cozy/apps/.first-install-import-from-google ]; then
+        if [ -d /usr/local/cozy/apps/import-from-google ]; then
+            touch /usr/local/cozy/apps/.first-install-import-from-google
+        else
+            cozy-monitor install import-from-google -r https://github.com/cozy-labs/import-from-google.git && touch /usr/local/cozy/apps/.first-install-import-from-google
+        fi
+    fi
 
-	msg_blue "This version of the Cozy package does not come with any configuration for reverse proxying, which is crucial for the platform's well behaviour. In order for the platform to work, please configure a reverse proxy.\nMore Information, please visit https://github.com/babolivier/cozy-archlinux#packages-description"
+    curl https://raw.githubusercontent.com/cozy/cozy-debian/master/debian-reconfigure-cozy-domain.sh > /usr/local/sbin/debian-reconfigure-cozy-domain.sh
+    chmod +x /usr/local/sbin/debian-reconfigure-cozy-domain.sh
+    echo "cozy-self-hosting ALL=NOPASSWD: /usr/local/sbin/debian-reconfigure-cozy-domain.sh" >> /etc/sudoers
+    if [ ! -f /usr/local/cozy/apps/.first-install-self-hosting ]; then
+        if [ -d /usr/local/cozy/apps/self-hosting ]; then
+            touch /usr/local/cozy/apps/.first-install-self-hosting
+        else
+            cozy-monitor install self-hosting -r https://github.com/cozy/cozy-self-hosting.git && touch /usr/local/cozy/apps/.first-install-self-hosting
+        fi
+    fi
+
+
+    msg "This version of the Cozy package does not come with any configuration for reverse proxying, which is crucial for the platform's well behaviour. In order for the platform to work, please configure a reverse proxy.\nFor more information, please visit https://github.com/babolivier/cozy-archlinux#packages-description"
+    echo "Before being able to try Cozy, you need to run the first-time-configuration script:"
+    echo "    # /usr/bin/configure-cozy cozy.example.tld"
+    echo "With your Cozy's own domain instead of \"cozy.example.tld\""
+}
+
+pre_remove() {
+    which cozy-monitor >/dev/null 2>&1
+    RESULT=$?
+    if [ "$RESULT" = "0" ]; then
+        APPS="$(cozy-monitor status | grep -vE '(mta|postfix|couch|controller|data-system|ds|home|proxy)' | sed 's/:.*//;s/\[Error//' | xargs echo)"
+        APPS="$APPS proxy home data-system"
+        for app in $APPS ; do cozy-monitor uninstall $app ; done
+    fi
+    which supervisorctl >/dev/null 2>&1 && supervisorctl stop cozy-controller
 }
 
 post_remove() {
-	msg_blue "The Cozy database contains all your user data. Keeping it could be troublesome for further installations."
-	while true; do
-		read -p "Do you want to erase the database? [Y/n] " yn
-		case $yn in
-		    [Nn]* ) KEEP_DB=false; break;;
-		    * ) KEEP_DB=true; break;;
-		esac
-	done
+    echo "The Cozy database contains all your user data. Keeping it could be troublesome for further installations. It will not be removed, unless you run"
+    echo "    # /usr/bin/cozy-rm-db"
+    mv /etc/cozy/couchdb.login /tmp/couchdb.login
+    echo "Moved the admin logins to /tmp/couch.login"
+    echo "Please don't forget to move it elsewhere if you don't want to lose access to your whole database."
 
-	if [ $KEEP_DB ]; then
-		COUCH_USER=$(sed -n '1,1p' /etc/cozy/couchdb.login)
-		COUCH_PASS=$(sed -n '2,1p' /etc/cozy/couchdb.login)
-		msg_blue "Purging cozy database"
-		curl -X DELETE http://${COUCH_USER}:${COUCH_PASS}@127.0.0.1:5984/cozy
-		msg_blue "Purging CouchDB cozy user"
-		curl -X DELETE http://${COUCH_USER}:${COUCH_PASS}@127.0.0.1:5984/_config/admins/${COUCH_USER}
-	else
-		msg_blue "Keeping the Cozy database"
-	fi
-	[ -d /etc/cozy ] && msg_blue "Deleting /etc/cozy directory" && rm -rf /etc/cozy
-	[ -d /usr/local/var/log/cozy ] && msg_blue "Deleting /usr/local/var/log/cozy directory" && rm -rf /usr/local/var/log/cozy
-	[ -d /usr/local/cozy ] && msg_blue "Deleting /usr/local/cozy directory" && rm -rf /usr/local/cozy
-	[ -d /var/lib/cozy-indexer ] && msg_blue "Deleting /var/lib/cozy-indexer directory" && rm -rf /var/lib/cozy-indexer
-	msg_blue "Erasing supervisor configuration" && rm /etc/supervisor.d/cozy*
-	supervisorctl reload
+    [ -d /etc/cozy ] && msg "Deleting /etc/cozy directory" && rm -rf /etc/cozy
+    [ -d /usr/local/var/log/cozy ] && msg "Deleting /usr/local/var/log/cozy directory" && rm -rf /usr/local/var/log/cozy
+    [ -d /usr/local/cozy ] && msg "Deleting /usr/local/cozy directory" && rm -rf /usr/local/cozy
+    msg "Erasing scripts and folders"
+    [ -f /usr/local/sbin/debian-reconfigure-cozy-domain.sh ] && rm -f /usr/local/sbin/debian-reconfigure-cozy-domain.sh
+    [ -d /usr/local/var/cozy ] && rm -rf /usr/local/var/cozy
+    [ -d /usr/share/cozy ] && rm -rf /usr/share/cozy
+    msg "Removing NPM dependencies"
+    [ -f /usr/bin/cozy-controller ] && npm remove -g cozy-controller
+    [ -f /usr/bin/cozy-controller ] && npm remove -g cozy-monitor
+    msg "Removing supervisor configuration" && rm /etc/supervisor.d/cozy*
+    supervisorctl reload
+}
+
+post_upgrade() {
+    # Since the last version, we added a new app for self-hosted users
+    msg "Applying latest updates"
+    curl https://raw.githubusercontent.com/cozy/cozy-debian/master/debian-reconfigure-cozy-domain.sh > /usr/local/sbin/debian-reconfigure-cozy-domain.sh
+    chmod +x /usr/local/sbin/debian-reconfigure-cozy-domain.sh
+    echo "cozy-self-hosting ALL=NOPASSWD: /usr/local/sbin/debian-reconfigure-cozy-domain.sh" >> /etc/sudoers
+    if [ ! -f /usr/local/cozy/apps/.first-install-self-hosting ]; then
+        if [ -d /usr/local/cozy/apps/self-hosting ]; then
+            touch /usr/local/cozy/apps/.first-install-self-hosting
+        else
+            cozy-monitor install self-hosting -r https://github.com/cozy/cozy-self-hosting.git && touch /usr/local/cozy/apps/.first-install-self-hosting
+        fi
+    fi
 }
