verify config restore before delete

diff --git a/crowdsec-bin.install b/crowdsec-bin.install
--- a/crowdsec-bin.install
+++ b/crowdsec-bin.install
@@ -23,8 +23,8 @@ pre_upgrade() {
 post_upgrade() {
     config_backup="/tmp/crowdsec_upgrade_$1_$2"
     if [ -d "$config_backup" ]; then
-        cscli config restore "$config_backup"
-        rm -rf "$config_backup"
+        cscli config restore "$config_backup" &&
+            rm -rf "$config_backup" || echo -e "\n**config backup restore failed: ${config_backup}**"
     fi
     cscli hub update
     cscli collections upgrade --all
