cyrus-imapd 3.0.9-1: New version

diff --git a/cyrus-imapd.install b/cyrus-imapd.install
--- a/cyrus-imapd.install
+++ b/cyrus-imapd.install
@@ -1,63 +1,32 @@
-# $Id: $
-#
-# Description: post-install script for cyrus-imapd
-# Contributor: Ryan Corder <ryanc@greengrey.org>
-#
-
-# arg 1: new package version
 post_install() {
-    # create cyrus user
-    if [ -z "`grep '^cyrus:' /etc/passwd`" ]; then
-        useradd -d /var/spool/imap -g mail -s /bin/false cyrus
-    else
-        usermod -s /bin/false cyrus
-    fi
-
-    # all kinds of directories needed for the IMAP spool
-    for subdir in imap/{,db,log,msg,proc,socket,sieve} spool/imap/{,stage.}; do
-        if [ ! -d /var/${subdir} ]; then
-            mkdir -m 0750 -p "/var/${subdir}"
-        fi
-    done
-    for subdir in imap/{user,quota,sieve} spool/imap; do
-        for i in a b c d e f g h i j k l m n o p q r s t v u w x y z \
-                 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z \
-                 0 1 2 3 4 5 6 7 8 9; do
-            if [ ! -d /var/${subdir}/${i} ]; then
-                mkdir -m 0750 -p "/var/${subdir}/${i}"
-            fi
-        done
-    done
-    chown -R cyrus:mail "/var/imap"
-    chown -R cyrus:mail "/var/spool/imap"
-
-    # make /var/imap/user/* and /var/imap/quota/* synchronous
-    if df -T /var/imap | grep -q ' ext[234] '; then
-        chattr +S /var/imap/{user,quota}{,/*}
-    fi
-    # make /var/spool/imap/* synchronous
-    if df -T /var/spool/imap | grep -q ' ext[23] '; then
-        chattr +S /var/spool/imap{,/*}
-    fi
-
-    # set more secure permissions on config files
-    chown -R cyrus:mail /etc/cyrus
-    chmod 600 /etc/cyrus/cyrus.conf
-    chmod 600 /etc/cyrus/imapd.conf
+  # For systems which previously used a cyrus-imapd package < 3.0: Create
+  # consistency with systems where user and group were created by
+  # systemd-sysusers (which doesn't touch existing users)
+  if ! getent group cyrus 2>&1 >/dev/null; then
+    groupadd -g 70 cyrus
+  fi
+  if getent passwd cyrus 2>&1 >/dev/null && [ $(id -u cyrus) -ne 70 ]; then
+    usermod -u 70 -g cyrus -c "Cyrus IMAP server" -d /var/lib/cyrus -s /sbin/nologin cyrus
+  fi
 }
 
-# arg 1: new package version
-# arg 2: old package version
 post_upgrade() {
-    post_install $1
+  post_install
+
+  if [ $(vercmp "$2" 3.0) -lt 0 ]; then
+    echo "Cyrus 3.0 contains major changes from previous versions, and so does the Arch"
+    echo "package. Please heed the following information to ensure a clean upgrade:"
+    echo "* For general information about upgrading to Cyrus 3.0 from previous versions,"
+    echo "  please read https://www.cyrusimap.org/imap/download/upgrade.html."
+    echo "* The suggested default paths /var/imap and /var/spool/imap have been changed"
+    echo "  to /var/lib/cyrus and /var/spool/cyrus. This change has been adopted in the"
+    echo "  Arch package, however if you want your existing installation to use these new"
+    echo "  paths, manual action is required."
+    echo "* On Arch, the cyrus user has been updated to use a fixed uid of 70. Please"
+    echo "  adjust any paths owned by that user accordingly, including the previously"
+    echo "  mentioned /var/imap and /var/spool/imap."
+    echo "* On Arch, the systemd unit has been renamed from cyrus-master.service to"
+    echo "  cyrus-imapd.service for consistency. If the unit was enabled before, you will"
+    echo "  have to re-enable it manually."
+  fi
 }
-
-# arg 1: old package version
-pre_remove() {
-    userdel cyrus &> /dev/null
-}
-
-op=$1
-shift
-
-$op $*
