SSet safe shell options and don't have a second argument to ERR since it is essentially unused and unmaintained

diff --git a/doasedit b/doasedit
--- a/doasedit
+++ b/doasedit
@@ -10,14 +10,17 @@ EDITOR=${EDITOR:-vi}
 
 ERR() {
     echo -e 'doasedit: '"$1";
-    exit $2;
+    exit 1
 }
 
-[[ $# == "0" ]] && ERR 'usage:\n\tdoasedit /file/owned/by/root\n\tdoasedit /new/file\t(starting a new file with "#!" will make it executable)' 4 # Argument was passed
+# Set shell options to fail if any variable expansion or final expression in a pipeline fails
+set -eu
+
+[[ $# == "0" ]] && ERR 'usage:\n\tdoasedit /file/owned/by/root\n\tdoasedit /new/file\t(starting a new file with "#!" will make it executable)' # Argument was passed
 # Ensure this script is run as a user who has doas priviledges, editing a regular or nonexistent file
-[[ "$(id -u)" == "0" ]] && ERR "Do not run doasedit as root!" 1
-/sbin/doas -C /etc/doas.conf doasedit \"$1\" >/dev/null || ERR "You are not a doer" 2 # To allow doasedit, you must be allowed to run `doas doasedit`
-[[ -d "$1" ]] && ERR "'$1' is a directory" 3; # File is a directory
+[[ "$(id -u)" == "0" ]] && ERR "Do not run doasedit as root!"
+/sbin/doas -C /etc/doas.conf doasedit \"$1\" >/dev/null || ERR "You are not a doer" # To allow doasedit, you must be allowed to run `doas doasedit`
+[[ -d "$1" ]] && ERR "'$1' is a directory" # File is a directory
 # Ensure the file is in a directory we can read
 [[ -d "`dirname $1`" ]] || ERR "'$1' is not in a directory we can read"
 [[ -r "`dirname $1`" ]] || ERR "'$1' is a directory you do not have permission to read"
@@ -27,26 +30,26 @@ if [[ -e "$1" ]] ; then
     fileperms=$(stat -L -c "%a" "$1")
     anyreadperm=${fileperms:3:1} # With sticky bit
     [[ ${#fileperms} == "3" ]] && anyreadperm=${fileperms:2:1} # without sticky bit
-    [[ $anyreadperm -ge "4" ]] || ERR "file '$1' is not world-readable (since security is hard, this is a sacrifice doasedit makes for ease of implementation)" 5
-    [[ -r "$1" ]] || ERR "file '$1' is world-readable but is not readable by your user, what are you doing?" 6
-    [[ "$(stat -L -c "%u" "$1")" == "0" ]] || ERR "Can only edit root-owned files with this script, as copying the file back will make root the owner" 7
+    [[ $anyreadperm -ge "4" ]] || ERR "file '$1' is not world-readable (since security is hard, this is a sacrifice doasedit makes for ease of implementation)"
+    [[ -r "$1" ]] || ERR "file '$1' is world-readable but is not readable by your user, what are you doing?"
+    [[ "$(stat -L -c "%u" "$1")" == "0" ]] || ERR "Can only edit root-owned files with this script, as copying the file back will make root the owner"
 
     # Preserves file permissions, amazingly
-    cp "$1" /tmp/doasediting || ERR "Cannot copy to /tmp/doasediting" 8
+    cp "$1" /tmp/doasediting || ERR "Cannot copy to /tmp/doasediting"
 else
     # Default permissions are 644
-    rm -f /tmp/doasediting || ERR "Cannot remove /tmp/doasediting" 9
-    touch /tmp/doasediting || ERR "Cannot touch /tmp/doasediting" 10
+    rm -f /tmp/doasediting || ERR "Cannot remove /tmp/doasediting"
+    touch /tmp/doasediting || ERR "Cannot touch /tmp/doasediting"
 fi
 
-$EDITOR /tmp/doasediting || ERR "The editor failed to exit successfully" 11
+$EDITOR /tmp/doasediting || ERR "The editor failed to exit successfully"
 
 # If the original file existed, don't update it if we did not make any modification to the temporary copy
 [[ -e "$1" ]] && cmp -s /tmp/doasediting "$1" && exit 0
 # If the original file did not exist, print a warning
 [[ -e "$1" ]] || echo "doasedit: File '$1' will be created, if this is not desireable press ctrl+C"
 
-doas cp /tmp/doasediting "$1" || ERR "You put your password in wrong. Manually run 'doas cp /tmp/doasediting $1'" 12
+doas cp /tmp/doasediting "$1" || ERR "You put your password in wrong. Manually run 'doas cp /tmp/doasediting $1'"
 
 # Change permissions if the file was empty and starts with a shebang
-[[ $fileperms != "" ]] || [[ `head -c 2 /tmp/doasediting` != "#!" ]] || { echo "doasedit: automatically running \`doas chmod +x '$1'\`" && doas chmod +x "$1" ; } || ERR "Cannot change permissions of '$1'" 13
+[[ $fileperms != "" ]] || [[ `head -c 2 /tmp/doasediting` != "#!" ]] || { echo "doasedit: automatically running \`doas chmod +x '$1'\`" && doas chmod +x "$1" ; } || ERR "Cannot change permissions of '$1'"
