Fix wrong install script

diff --git a/efistub-helper.install b/efistub-helper.install
--- a/efistub-helper.install
+++ b/efistub-helper.install
@@ -1,4 +1,15 @@
 post_install() {
+    esp=$(df --output=source /boot | sed -n '2p')
+    if [ -z "${esp}" ];then
+        esp=$(df --output=source /esp | sed -n '2p')
+        if [ -z "${esp}" ];then
+            echo -e "\033[31m Error: No boot partition or unsupported mount point. \033[0m" >&2
+            exit -1
+        fi
+    fi
+
+    disk="/dev/$(lsblk -no pkname ${esp})"
+    partnum=$(echo ${esp: ${#disk}} | tr -cd "[0-9]")
     cat>/etc/efistub.conf<<EOF
 start-bootnum: 0000
 disk: ${disk}
