Replaced evewinecfg and everegedit with symlinks to evewine which execute these commands now. Changes on build_installer.sh script to handle symlinks from evewinecfg and everegedit. Handle symlinks from everegedit and evewinecfg in setup.sh.in and PKGBUILD too.

diff --git a/evelauncher.sh.in b/evelauncher.sh.in
--- a/evelauncher.sh.in
+++ b/evelauncher.sh.in
@@ -55,17 +55,18 @@ check_wine() {
     EVECONF=$CONFDIR/EVE.conf
     UCW=$(grep UseCustomWine $EVECONF | cut -d= -f2)
     if [ "x$UCW" = "xtrue" ] ;then
-	WINEPATH=$(grep CustomWinePath $EVECONF | cut -d= -f2)
-	WINEPATH=${WINEPATH%/*}
+	CUSTOMWP=$(grep CustomWinePath $EVECONF | cut -d= -f2)
+	WINEPATH=${CUSTOMWP%/*}
+	SHAREDIR=$(grep SharedCacheFolder $EVECONF | cut -d= -f2)
+	WINEPREFIX=${SHAREDIR}wineenv
     else
-	launcher_msg "Error: Custom wine not set!"
+	launcher_msg "ERROR: \"Use custom Wine\" not set!"
 	exit 1
     fi
     WINEDATE=$(ls -l --time-style=+%s $WINEPATH/wineserver | cut -d' ' -f6)
-    INSTWINE=$(cat $EVEDIR/SharedCache/wineenv/.update-timestamp 2>/dev/null) || true
+    INSTWINE=$(cat $WINEPREFIX/.update-timestamp 2>/dev/null) || true
     if [ "x$WINEDATE" != "x$INSTWINE" ] ;then
 	if [ -x "$WINEPATH/wine" ] ;then
-	    WINEPREFIX=$EVEDIR/SharedCache/wineenv
 	    launcher_msg "Preparing/Updating wine in $WINEPREFIX"
 	    env WINEARCH=win32 \
 		WINEPREFIX=$WINEPREFIX \
@@ -81,7 +82,7 @@ check_wine() {
 	    env WINEPREFIX=$WINEPREFIX WINE=$WINEPATH/wine \
 		$(which winetricks) -q winxp >/dev/null
 	else
-	    launcher_msg "Error: No wine in $WINEPATH found!"
+	    launcher_msg "ERROR: \"$CUSTOMWP\" in \"Custom Wine path\" not found!"
 	    exit 1
 	fi
     fi
diff --git a/evewine b/evewine
--- a/evewine
+++ b/evewine
@@ -1,18 +1,23 @@
 #!/bin/sh
 
 EVECONF=$HOME/.config/CCP/EVE.conf
-EVEDIR=$HOME/.local/lib/EVE
-
 UCW=$(grep UseCustomWine $EVECONF | cut -d= -f2)
 if [ "x$UCW" = "xtrue" ] ;then
-    WINEPATH=$(grep CustomWinePath $EVECONF | cut -d= -f2)
-    WINEPATH=${WINEPATH%/*}
+    CUSTOMWP=$(grep CustomWinePath $EVECONF | cut -d= -f2)
+    WINEPATH=${CUSTOMWP%/*}
+    SHAREDIR=$(grep SharedCacheFolder $EVECONF | cut -d= -f2)
+    WINEPREFIX=${SHAREDIR}wineenv
 else
-    echo "$(basename $0): Error: Custom wine not set!"
+    echo "$(basename $0): ERROR: \"Use Custom Wine\" not set!"
+    exit 1
+fi
+if [ ! -x "$WINEPATH/wine" ] ;then
+    echo "$(basename $0): ERROR: \"$CUSTOMWP\" from \"Custom Wine path\" not found!"
+    echo "$(basename $0): The full path are required (example: /usr/bin/wine)."
     exit 1
 fi
 
-env WINEPREFIX=$HOME/.local/lib/EVE/SharedCache/wineenv \
+env WINEPREFIX=$WINEPREFIX \
     WINEDEBUG=-all \
     WINEDLLOVERRIDES="mscoree,mshtml,winemenubuilder.exe=d" \
-    $WINEPATH/wine "$@"
+    $WINEPATH/${0#*eve} "$@"
diff --git a/evewinetricks b/evewinetricks
--- a/evewinetricks
+++ b/evewinetricks
@@ -1,15 +1,20 @@
 #!/bin/sh
 
 EVECONF=$HOME/.config/CCP/EVE.conf
-EVEDIR=$HOME/.local/lib/EVE
-
 UCW=$(grep UseCustomWine $EVECONF | cut -d= -f2)
 if [ "x$UCW" = "xtrue" ] ;then
-    WINEPATH=$(grep CustomWinePath $EVECONF | cut -d= -f2)
+    CUSTOMWP=$(grep CustomWinePath $EVECONF | cut -d= -f2)
+    WINEPATH=${CUSTOMWP%/*}
+    SHAREDIR=$(grep SharedCacheFolder $EVECONF | cut -d= -f2)
+    WINEPREFIX=${SHAREDIR}wineenv
 else
-    echo "$(basename $0): Error: Custom wine not set!"
+    echo "$(basename $0): ERROR: \"Use Custom Wine\" not set!"
+    exit 1
+fi
+if [ ! -x "$WINEPATH/wine" ] ;then
+    echo "$(basename $0): ERROR: \"$CUSTOMWP\" in \"Custom Wine path\" not found!"
     exit 1
 fi
 
-env WINEPREFIX=$HOME/.local/lib/EVE/SharedCache/wineenv \
-    WINE=$WINEPATH $(which winetricks) "$@"
+env WINEPREFIX=$WINEPREFIX \
+    WINE=$WINEPATH/wine $(which winetricks) "$@"
