Large icons added. Chinese translations added. Changed $WINEPATH settings to handle whitespaces in path.

diff --git a/evelauncher.sh.in b/evelauncher.sh.in
--- a/evelauncher.sh.in
+++ b/evelauncher.sh.in
@@ -56,36 +56,39 @@ check_wine() {
     UCW=$(grep UseCustomWine $EVECONF | cut -d= -f2)
     if [ "x$UCW" = "xtrue" ] ;then
 	CUSTOMWP=$(grep CustomWinePath $EVECONF | cut -d= -f2)
-	WINEPATH=${CUSTOMWP%/*}
+	WINEPATH="${CUSTOMWP%/*}"
 	SHAREDIR=$(grep SharedCacheFolder $EVECONF | cut -d= -f2)
 	WINEPREFIX=${SHAREDIR}wineenv
     else
 	launcher_msg "ERROR: \"Use custom Wine\" not set!"
 	exit 1
     fi
-    WINESERVER=$(readlink -f $WINEPATH/wineserver)
-    WINEDATE=$(ls -l --time-style=+%s $WINESERVER | cut -d' ' -f6)
-    INSTWINE=$(cat $WINEPREFIX/.update-timestamp 2>/dev/null) || true
-    if [ "x$WINEDATE" != "x$INSTWINE" ] ;then
-	if [ -x "$WINEPATH/wine" ] ;then
+    if [ -x "$WINEPATH/wine" ] ;then
+	INSTWINE=$(cat $WINEPREFIX/.update-timestamp 2>/dev/null) || true
+	for CMD in wine wine64 wineserver ;do
+	    WINECMD=$(readlink -f "$WINEPATH/$CMD")
+	    WINEDATE=$(ls -l --time-style=+%s "$WINECMD" 2>/dev/null | cut -d' ' -f6)
+	    test "x$WINEDATE" = "x$INSTWINE" && break
+	done
+	if [ "x$WINEDATE" != "x$INSTWINE" ] ;then
 	    launcher_msg "Preparing/Updating wine in $WINEPREFIX"
 	    env WINEARCH=win32 \
 		WINEPREFIX=$WINEPREFIX \
 		WINEDEBUG=-all \
 		WINEDLLOVERRIDES="mscoree,mshtml,winemenubuilder.exe=d" \
-		$WINEPATH/wine wineboot
-	    env WINEPREFIX=$WINEPREFIX $WINEPATH/wine reg delete \
+		"$WINEPATH/wine" wineboot
+	    env WINEPREFIX=$WINEPREFIX "$WINEPATH/wine" reg delete \
 		'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunServices' \
 		/v winemenubuilder /f >/dev/null || true
-	    env WINEPREFIX=$WINEPREFIX $WINEPATH/wine reg add \
+	    env WINEPREFIX=$WINEPREFIX "$WINEPATH/wine" reg add \
 		'HKEY_CURRENT_USER\Software\Wine\DllOverrides' \
 		/v winemenubuilder.exe /f >/dev/null
-	    env WINEPREFIX=$WINEPREFIX WINE=$WINEPATH/wine \
+	    env WINEPREFIX=$WINEPREFIX WINE="$WINEPATH/wine" \
 		$(which winetricks) -q winxp >/dev/null
-	else
-	    launcher_msg "ERROR: \"$CUSTOMWP\" in \"Custom Wine path\" not found!"
-	    exit 1
 	fi
+    else
+	launcher_msg "ERROR: \"$CUSTOMWP\" in \"Custom Wine path\" not found!"
+	exit 1
     fi
 }
 
