Update install file, arm package, v1.4.5

diff --git a/expressvpn.install b/expressvpn.install
--- a/expressvpn.install
+++ b/expressvpn.install
@@ -6,7 +6,7 @@ post_install() {
   /usr/bin/printf " Then activate your expressVPN account with\n"
   /usr/bin/printf "     $ expressvpn activate [activation code]\n"
   /usr/bin/printf " (Your activation code can be found at\n"
-  /usr/bin/printf " https://www.expressvpn.com/licenses/current)\n"
+  /usr/bin/printf " https://www.expressvpn.com/subscriptions)\n"
   /usr/bin/printf "\n"
   /usr/bin/printf " Once activated, Use 'expressvpn list' to\n"
   /usr/bin/printf " list servers and 'expressvpn connect [id]' \n"
@@ -38,9 +38,9 @@ post_upgrade() {
     /usr/bin/printf "------------------------------------------------------------------------------\n"
   fi
   /usr/bin/printf "------------------------------------------------\n"
-  /usr/bin/printf " You may need to restart the expressvpn daemon:\n"
+  /usr/bin/printf " You will need to restart the expressvpn daemon:\n"
   /usr/bin/printf "     # systemctl daemon-reload\n"
-  /usr/bin/printf "     # systemctl restart expressvpn.service\n"
+  /usr/bin/printf "     # systemctl start expressvpn.service\n"
   /usr/bin/printf "------------------------------------------------\n"
 }
 
@@ -50,4 +50,33 @@ post_remove() {
   /usr/bin/rm -f /var/lib/expressvpn/certs/client.p12
   /usr/bin/rm -f /var/lib/expressvpn/certs/clientca.crt
   /usr/bin/rm -f /var/lib/expressvpn/certs/clientca.key
+}
+
+pre_remove() {
+  # Disconnect before remove. OK to fail.
+  if /usr/bin/expressvpn status 2>/dev/null | grep -q Connected; then
+	  /usr/bin/expressvpn disconnect > /dev/null 2>&1 || true
+  fi
+
+  # Stop engine daemon
+  if [ -x /usr/bin/systemctl ]; then
+	  /usr/bin/systemctl stop expressvpn &>/dev/null
+  fi
+}
+
+pre_upgrade() {
+  pre_remove
+  if grep -q "Generated by expressvpn" /etc/resolv.conf; then
+    # reset chattr
+    [ -x /usr/bin/chattr ] && /usr/bin/chattr -i /etc/resolv.conf &>/dev/null || true
+    
+    # restore previous resolv.conf
+    bakfile=/var/lib/expressvpn/resolv.conf.orig
+    if [ -L "$bakfile" ]; then
+      mv "$bakfile" /etc/resolv.conf
+    elif [ -f "$bakfile" ]; then
+      cat "$bakfile" > /etc/resolv.conf
+      rm /var/lib/expressvpn/resolv.conf.orig
+    fi
+  fi
 }
