Fail loaders if fusemount fails

diff --git a/gog-heroes-of-might-and-magic-3-complete-edition-map-editor b/gog-heroes-of-might-and-magic-3-complete-edition-map-editor
--- a/gog-heroes-of-might-and-magic-3-complete-edition-map-editor
+++ b/gog-heroes-of-might-and-magic-3-complete-edition-map-editor
@@ -11,7 +11,11 @@ then
 fi
 if ! mountpoint "${UNIONFS_MNT}"
 then
-  unionfs -o cow,allow_other,relaxed_permissions,use_ino,suid,dev,nonempty ${DATA_DIR}=RW:${SOURCE}=RO "${UNIONFS_MNT}"
+  if ! unionfs -o cow,allow_other,relaxed_permissions,use_ino,suid,dev,nonempty ${DATA_DIR}=RW:${SOURCE}=RO "${UNIONFS_MNT}"
+  then
+    echo "Failed to mount unionfs" >&2
+    exit 1
+  fi
 fi
 cd "${UNIONFS_MNT}"
 wine h3maped.exe "$@"
