rework hook; add verify signature function

diff --git a/hooks-encrypt b/hooks-encrypt
--- a/hooks-encrypt
+++ b/hooks-encrypt
@@ -1,20 +1,6 @@
 #!/usr/bin/ash
 # shellcheck shell=dash
 
-_verify_signature() {
-    local _status
-    local _file="${1}"
-    local _sigfile="${2}"
-    local _dir _filename
-    _dir="$(dirname "${_file}")"
-    _filename="$(basename "${_file}")"
-    cd "${_dir}" || exit 1
-    gpg --homedir /gpg --status-fd 1 --verify "${_sigfile}" "${_filename}" 2>/dev/null | grep -E '^\[GNUPG:\] GOODSIG'
-    _status=$?
-    cd -- "${OLDPWD}" || exit 1
-    return ${_status}
-}
-
 _get_key() {
     ckeyfile="/crypto_keyfile.bin"
     IFS=: read ckdev ckarg1 ckarg2 <<EOF
@@ -49,7 +35,7 @@ EOF
                     mount --mkdir -r -t "$ckfs2" "${ckey}" /ckey2
                     ckey="/ckey2/${ckpath2}"
                 fi
-                dd if="${ckey}" of="$ckeyfile" >/dev/null 2>&1
+                dd if="${ckey}" of="${ckeyfile}" >/dev/null 2>&1
                 if mountpoint -q /ckey2; then
                     umount /ckey2
                     cryptsetup close --type luks ckey;
@@ -59,14 +45,46 @@ EOF
             *)
                 # Read raw data from the block device
                 # ckarg1 is numeric: ckarg1=offset, ckarg2=length
-                dd if="$resolved" of="$ckeyfile" bs=1 skip="$ckarg1" count="$ckarg2" >/dev/null 2>&1
+                dd if="${resolved}" of="${ckeyfile}" bs=1 skip="${ckarg1}" count="${ckarg2}" >/dev/null 2>&1
                 ;;
         esac
     fi
-    [ ! -f ${ckeyfile} ] && echo "Keyfile could not be opened. Reverting to passphrase."
+    [ ! -f "${ckeyfile}" ] && echo "Keyfile could not be opened. Reverting to passphrase."
 }
 
-_get_cryptdev() {
+_sigdev() {
+    local _sigdev _sigpath
+    if [ -n "${sigdevice}" ]; then
+        DEPRECATED_CRYPT=0
+        IFS=: read _sigdev _sigpath <<EOF
+$sigdevice
+EOF
+        if mount --mkdir -o "defaults" "${_sigdev}" /run/sigdev; then
+            echo "Device ${_sigdev} mounted successfully over /run/sigdev"
+            sigfile="/run/sigdev/${_sigpath}"
+            dd if="${sigfile}" of="/sigfile" >/dev/null 2>&1
+        else
+            echo "Can't mount device ${_sigdev} over /run/sigdev"
+        fi
+
+    fi
+}
+
+_verify_signature() {
+    local _status
+    local _file="${1}"
+    local _sigfile="${2}"
+    local _dir _filename
+    _dir="$(dirname "${_file}")"
+    _filename="$(basename "${_file}")"
+    cd "${_dir}" || exit 1
+    gpg --homedir /gpg --status-fd 1 --verify "${_sigfile}" "${_filename}" 2>/dev/null | grep -E '^\[GNUPG:\] GOODSIG'
+    _status=$?
+    cd -- "${OLDPWD}" || exit 1
+    return ${_status}
+}
+
+_cryptdev() {
     if [ -n "${cryptdevice}" ]; then
         DEPRECATED_CRYPT=0
         IFS=: read cryptdev cryptname cryptoptions <<EOF
@@ -121,7 +139,7 @@ warn_deprecated() {
     echo "Use 'cryptdevice=${root}:root root=/dev/mapper/root' instead."
 }
 
-_mount_root() {
+_open_root() {
     resolved=$(cryptsetup isLuks "${cryptdev}" >/dev/null 2>&1 && echo "${cryptdev}")
     [ "${resolved}" = "" ] && resolved=$(resolve_device "${cryptdev}" ${rootdelay})
     if [ "${resolved}" != "" ]; then
@@ -129,7 +147,7 @@ _mount_root() {
             [ ${DEPRECATED_CRYPT} -eq 1 ] && warn_deprecated
             dopassphrase=1
             # If keyfile exists, try to use that
-            if [ -f ${ckeyfile} ]; then
+            if [ -f "${ckeyfile}" ]; then
                 if eval cryptsetup --key-file ${ckeyfile} open --type luks ${resolved} ${cryptname} ${cryptargs} ${CSQUIET}; then
                     dopassphrase=0
                 else
@@ -199,11 +217,24 @@ EOF
 }
 
 run_hook() {
-    # shellcheck disable=SC2154
     modprobe -a -q dm-crypt >/dev/null 2>&1
+    # shellcheck disable=SC2154
     [ "${quiet}" = "y" ] && CSQUIET=">/dev/null"
 
-    _get_cryptdev
+
+    _cryptdev
+    _sigdev
+
+    # shellcheck disable=SC2154
+    if [ "${verify}" = "y" ]; then 
+       if _verify_signature "${cryptdev}" "/sigfile"; then
+           msg "Signature is OK, continue booting."
+           export verify="n"
+       else
+           echo "ERROR: one or more files are corrupted"
+           launch_interactive_shell
+       fi
+    fi
 
     # Get keyfile if specified
     ckeyfile="/crypto_keyfile.bin"
@@ -218,8 +249,9 @@ run_hook() {
     fi
 
     _set_cryptargs
-    _mount_root
+    _open_root
     rm -f ${ckeyfile}
+    rm -f "${sigfile}"
 }
 
 # vim: set ft=sh ts=4 sw=4 et:
