Upgrade to 2.1.0

diff --git a/installer_sh_x86.patch b/installer_sh_x86.patch
--- a/installer_sh_x86.patch
+++ b/installer_sh_x86.patch
@@ -1,32 +1,32 @@
---- a/Anaconda-2.0.1-Linux-x86.sh	2014-06-12 22:37:04.000000000 +0200
-+++ b/Anaconda-2.0.1-Linux-x86.sh	2014-06-16 20:32:39.822150622 +0200
+--- a/Anaconda-2.1.0-Linux-x86.sh	2014-11-12 23:50:23.679702864 +0100
++++ b/Anaconda-2.1.0-Linux-x86.sh	2014-11-12 23:51:05.023232368 +0100
 @@ -73,9 +73,9 @@
      fi
  fi
  # verify the size of the installer
--wc -c "$THIS_PATH" | grep 324151704 >/dev/null
-+wc -c "$THIS_PATH" | grep 324151711 >/dev/null
+-wc -c "$THIS_PATH" | grep 336767704 >/dev/null
++wc -c "$THIS_PATH" | grep 336767711 >/dev/null
  if (( $? )); then
--    echo "ERROR: size of $THIS_FILE should be 324151704 bytes" >&2
-+    echo "ERROR: size of $THIS_FILE should be 324151711 bytes" >&2
+-    echo "ERROR: size of $THIS_FILE should be 336767704 bytes" >&2
++    echo "ERROR: size of $THIS_FILE should be 336767711 bytes" >&2
      exit 1
  fi
  
-@@ -381,7 +381,7 @@
+@@ -390,7 +390,7 @@
  extract_dist _cache-0.0-x0
  
  mkdir $PREFIX/envs
 -mkdir $HOME/.continuum 2>/dev/null
 +#mkdir $HOME/.continuum 2>/dev/null
  
- PYTHON="$PREFIX/pkgs/python-2.7.7-0/bin/python -E"
+ PYTHON="$PREFIX/pkgs/python-2.7.8-1/bin/python -E"
  $PYTHON -V
-@@ -391,7 +391,7 @@
+@@ -400,7 +400,7 @@
      uname -a
      exit 1
  fi
 -
 +exit 0
  echo "creating default environment..."
- CONDA_INSTALL="$PREFIX/pkgs/conda-3.5.5-py27_0/lib/python2.7/site-packages/conda/install.py"
+ CONDA_INSTALL="$PREFIX/pkgs/conda-3.7.0-py27_0/lib/python2.7/site-packages/conda/install.py"
  $PYTHON $CONDA_INSTALL --prefix=$PREFIX --pkgs-dir=$PREFIX/pkgs --link-all || exit 1
diff --git a/installer_sh_x86_64.patch b/installer_sh_x86_64.patch
--- a/installer_sh_x86_64.patch
+++ b/installer_sh_x86_64.patch
@@ -1,32 +1,32 @@
---- a/Anaconda-2.0.1-Linux-x86_64.sh	2014-06-12 22:17:47.000000000 +0200
-+++ b/Anaconda-2.0.1-Linux-x86_64.sh	2014-06-16 20:36:49.851490759 +0200
+--- a/Anaconda-2.1.0-Linux-x86_64.sh	2014-11-12 23:29:42.485872636 +0100
++++ b/Anaconda-2.1.0-Linux-x86_64.sh	2014-11-12 23:30:25.093384629 +0100
 @@ -70,9 +70,9 @@
      fi
  fi
  # verify the size of the installer
--wc -c "$THIS_PATH" | grep 343791922 >/dev/null
-+wc -c "$THIS_PATH" | grep 343791929 >/dev/null
+-wc -c "$THIS_PATH" | grep 353806962 >/dev/null
++wc -c "$THIS_PATH" | grep 353806969 >/dev/null
  if (( $? )); then
--    echo "ERROR: size of $THIS_FILE should be 343791922 bytes" >&2
-+    echo "ERROR: size of $THIS_FILE should be 343791929 bytes" >&2
+-    echo "ERROR: size of $THIS_FILE should be 353806962 bytes" >&2
++    echo "ERROR: size of $THIS_FILE should be 353806969 bytes" >&2
      exit 1
  fi
  
-@@ -380,7 +380,7 @@
+@@ -389,7 +389,7 @@
  extract_dist _cache-0.0-x0
  
  mkdir $PREFIX/envs
 -mkdir $HOME/.continuum 2>/dev/null
 +#mkdir $HOME/.continuum 2>/dev/null
  
- PYTHON="$PREFIX/pkgs/python-2.7.7-0/bin/python -E"
+ PYTHON="$PREFIX/pkgs/python-2.7.8-1/bin/python -E"
  $PYTHON -V
-@@ -390,7 +390,7 @@
+@@ -399,7 +399,7 @@
      uname -a
      exit 1
  fi
 -
 +exit 0
  echo "creating default environment..."
- CONDA_INSTALL="$PREFIX/pkgs/conda-3.5.5-py27_0/lib/python2.7/site-packages/conda/install.py"
+ CONDA_INSTALL="$PREFIX/pkgs/conda-3.7.0-py27_0/lib/python2.7/site-packages/conda/install.py"
  $PYTHON $CONDA_INSTALL --prefix=$PREFIX --pkgs-dir=$PREFIX/pkgs --link-all || exit 1
