Upgrade to 2.5.0

diff --git a/installer_sh_x86.patch b/installer_sh_x86.patch
--- a/installer_sh_x86.patch
+++ b/installer_sh_x86.patch
@@ -1,32 +1,32 @@
---- a/Anaconda2-2.4.1-Linux-x86.sh	2015-12-14 20:47:32.936750931 +0100
-+++ b/Anaconda2-2.4.1-Linux-x86.sh	2015-12-14 21:09:17.543139737 +0100
+--- a/Anaconda2-2.5.0-Linux-x86.sh	2016-02-22 13:11:18.202366701 +0100
++++ b/Anaconda2-2.5.0-Linux-x86.sh	2016-02-22 13:12:51.364710292 +0100
 @@ -73,9 +73,9 @@
      fi
  fi
  # verify the size of the installer
--wc -c "$THIS_PATH" | grep 260583576 >/dev/null
-+wc -c "$THIS_PATH" | grep 260583583 >/dev/null
+-wc -c "$THIS_PATH" | grep 346405513 >/dev/null
++wc -c "$THIS_PATH" | grep 346405520 >/dev/null
  if (( $? )); then
--    echo "ERROR: size of $THIS_FILE should be 260583576 bytes" >&2
-+    echo "ERROR: size of $THIS_FILE should be 260583583 bytes" >&2
+-    echo "ERROR: size of $THIS_FILE should be 346405513 bytes" >&2
++    echo "ERROR: size of $THIS_FILE should be 346405520 bytes" >&2
      exit 1
  fi
  
-@@ -439,7 +439,7 @@
- extract_dist anaconda-2.4.1-np110py27_0
+@@ -446,7 +446,7 @@
+ extract_dist conda-env-2.4.5-py27_0
  
  mkdir $PREFIX/envs
 -mkdir $HOME/.continuum 2>/dev/null
 +#mkdir $HOME/.continuum 2>/dev/null
  
- PYTHON="$PREFIX/pkgs/python-2.7.11-0/bin/python -E"
- $PYTHON -V
-@@ -449,7 +449,7 @@
+ PYTHON="$PREFIX/pkgs/python-2.7.11-0/bin/python"
+ $PYTHON -E -V
+@@ -456,7 +456,7 @@
      uname -a
      exit 1
  fi
 -
 +exit 0
  echo "creating default environment..."
- CONDA_INSTALL="$PREFIX/pkgs/conda-3.18.8-py27_0/lib/python2.7/site-packages/conda/install.py"
- $PYTHON $CONDA_INSTALL --prefix=$PREFIX --pkgs-dir=$PREFIX/pkgs --link-all || exit 1
+ CONDA_INSTALL="$PREFIX/pkgs/conda-3.19.1-py27_0/lib/python2.7/site-packages/conda/install.py"
+ $PYTHON -E -s $CONDA_INSTALL --prefix=$PREFIX --file=conda-meta/.ilan || exit 1
diff --git a/installer_sh_x86_64.patch b/installer_sh_x86_64.patch
--- a/installer_sh_x86_64.patch
+++ b/installer_sh_x86_64.patch
@@ -1,32 +1,32 @@
---- a/Anaconda2-2.4.1-Linux-x86_64.sh	2015-12-14 20:47:32.796752390 +0100
-+++ b/Anaconda2-2.4.1-Linux-x86_64.sh	2015-12-14 21:10:02.742667263 +0100
+--- a/Anaconda2-2.5.0-Linux-x86_64.sh	2016-02-22 13:11:18.035701806 +0100
++++ b/Anaconda2-2.5.0-Linux-x86_64.sh	2016-02-22 13:14:02.023959621 +0100
 @@ -70,9 +70,9 @@
      fi
  fi
  # verify the size of the installer
--wc -c "$THIS_PATH" | grep 277827702 >/dev/null
-+wc -c "$THIS_PATH" | grep 277827709 >/dev/null
+-wc -c "$THIS_PATH" | grep 409842279 >/dev/null
++wc -c "$THIS_PATH" | grep 409842286 >/dev/null
  if (( $? )); then
--    echo "ERROR: size of $THIS_FILE should be 277827702 bytes" >&2
-+    echo "ERROR: size of $THIS_FILE should be 277827709 bytes" >&2
+-    echo "ERROR: size of $THIS_FILE should be 409842279 bytes" >&2
++    echo "ERROR: size of $THIS_FILE should be 409842286 bytes" >&2
      exit 1
  fi
  
-@@ -440,7 +440,7 @@
- extract_dist anaconda-2.4.1-np110py27_0
+@@ -447,7 +447,7 @@
+ extract_dist conda-env-2.4.5-py27_0
  
  mkdir $PREFIX/envs
 -mkdir $HOME/.continuum 2>/dev/null
 +#mkdir $HOME/.continuum 2>/dev/null
  
- PYTHON="$PREFIX/pkgs/python-2.7.11-0/bin/python -E"
- $PYTHON -V
-@@ -450,7 +450,7 @@
+ PYTHON="$PREFIX/pkgs/python-2.7.11-0/bin/python"
+ $PYTHON -E -V
+@@ -457,7 +457,7 @@
      uname -a
      exit 1
  fi
 -
 +exit 0
  echo "creating default environment..."
- CONDA_INSTALL="$PREFIX/pkgs/conda-3.18.8-py27_0/lib/python2.7/site-packages/conda/install.py"
- $PYTHON $CONDA_INSTALL --prefix=$PREFIX --pkgs-dir=$PREFIX/pkgs --link-all || exit 1
+ CONDA_INSTALL="$PREFIX/pkgs/conda-3.19.1-py27_0/lib/python2.7/site-packages/conda/install.py"
+ $PYTHON -E -s $CONDA_INSTALL --prefix=$PREFIX --file=conda-meta/.ilan || exit 1
