Upgrade to 2.0.0

diff --git a/installer_sh_x86.patch b/installer_sh_x86.patch
--- a/installer_sh_x86.patch
+++ b/installer_sh_x86.patch
@@ -1,32 +1,32 @@
---- a/Anaconda-1.9.2-Linux-x86.sh	2014-04-13 19:38:45.647043146 +0200
-+++ b/Anaconda-1.9.2-Linux-x86.sh	2014-04-13 19:57:08.897523021 +0200
-@@ -68,9 +68,9 @@
+--- a/Anaconda-2.0.0-Linux-x86.sh	2014-05-29 01:35:31.087202509 +0200
++++ b/Anaconda-2.0.0-Linux-x86.sh	2014-05-29 01:36:33.366571125 +0200
+@@ -73,9 +73,9 @@
      fi
  fi
  # verify the size of the installer
--wc -c "$THIS_PATH" | grep 431825310 >/dev/null
-+wc -c "$THIS_PATH" | grep 431825317 >/dev/null
+-wc -c "$THIS_PATH" | grep 312856983 >/dev/null
++wc -c "$THIS_PATH" | grep 312856990 >/dev/null
  if (( $? )); then
--    echo "ERROR: size of $THIS_FILE should be 431825310 bytes" >&2
-+    echo "ERROR: size of $THIS_FILE should be 431825317 bytes" >&2
+-    echo "ERROR: size of $THIS_FILE should be 312856983 bytes" >&2
++    echo "ERROR: size of $THIS_FILE should be 312856990 bytes" >&2
      exit 1
  fi
  
-@@ -382,7 +382,7 @@
+@@ -381,7 +381,7 @@
  extract_dist _cache-0.0-x0
  
  mkdir $PREFIX/envs
 -mkdir $HOME/.continuum 2>/dev/null
 +#mkdir $HOME/.continuum 2>/dev/null
  
- PYTHON="$PREFIX/pkgs/python-2.7.6-0/bin/python -E"
+ PYTHON="$PREFIX/pkgs/python-2.7.6-2/bin/python -E"
  $PYTHON -V
-@@ -392,7 +392,7 @@
+@@ -391,7 +391,7 @@
      uname -a
      exit 1
  fi
 -
 +exit 0
  echo "creating default environment..."
- CONDA_INSTALL="$PREFIX/pkgs/conda-3.4.1-py27_0/lib/python2.7/site-packages/conda/install.py"
+ CONDA_INSTALL="$PREFIX/pkgs/conda-3.5.2-py27_0/lib/python2.7/site-packages/conda/install.py"
  $PYTHON $CONDA_INSTALL --prefix=$PREFIX --pkgs-dir=$PREFIX/pkgs --link-all || exit 1
diff --git a/installer_sh_x86_64.patch b/installer_sh_x86_64.patch
--- a/installer_sh_x86_64.patch
+++ b/installer_sh_x86_64.patch
@@ -1,32 +1,32 @@
---- a/Anaconda-1.9.2-Linux-x86_64.sh	2014-04-13 19:38:45.895040134 +0200
-+++ b/Anaconda-1.9.2-Linux-x86_64.sh	2014-04-13 19:42:32.848287866 +0200
-@@ -65,9 +65,9 @@
+--- a/Anaconda-2.0.0-Linux-x86_64.sh	2014-05-29 00:27:10.915553152 +0200
++++ b/Anaconda-2.0.0-Linux-x86_64.sh	2014-05-29 00:28:54.674366396 +0200
+@@ -70,9 +70,9 @@
      fi
  fi
  # verify the size of the installer
--wc -c "$THIS_PATH" | grep 507498869 >/dev/null
-+wc -c "$THIS_PATH" | grep 507498876 >/dev/null
+-wc -c "$THIS_PATH" | grep 332323121 >/dev/null
++wc -c "$THIS_PATH" | grep 332323128 >/dev/null
  if (( $? )); then
--    echo "ERROR: size of $THIS_FILE should be 507498869 bytes" >&2
-+    echo "ERROR: size of $THIS_FILE should be 507498876 bytes" >&2
+-    echo "ERROR: size of $THIS_FILE should be 332323121 bytes" >&2
++    echo "ERROR: size of $THIS_FILE should be 332323128 bytes" >&2
      exit 1
  fi
  
-@@ -383,7 +383,7 @@
+@@ -380,7 +380,7 @@
  extract_dist _cache-0.0-x0
  
  mkdir $PREFIX/envs
 -mkdir $HOME/.continuum 2>/dev/null
 +#mkdir $HOME/.continuum 2>/dev/null
  
- PYTHON="$PREFIX/pkgs/python-2.7.6-1/bin/python -E"
+ PYTHON="$PREFIX/pkgs/python-2.7.6-2/bin/python -E"
  $PYTHON -V
-@@ -393,7 +393,7 @@
+@@ -390,7 +390,7 @@
      uname -a
      exit 1
  fi
 -
 +exit 0
  echo "creating default environment..."
- CONDA_INSTALL="$PREFIX/pkgs/conda-3.4.1-py27_0/lib/python2.7/site-packages/conda/install.py"
+ CONDA_INSTALL="$PREFIX/pkgs/conda-3.5.2-py27_0/lib/python2.7/site-packages/conda/install.py"
  $PYTHON $CONDA_INSTALL --prefix=$PREFIX --pkgs-dir=$PREFIX/pkgs --link-all || exit 1
