Improve config handling during updates

diff --git a/intelpwm b/intelpwm
--- a/intelpwm
+++ b/intelpwm
@@ -1,5 +1,11 @@
 #!/usr/bin/env sh
-source /etc/intelpwm.conf
+CONFIG=/etc/intelpwm.conf
+if [ ! -f "$CONFIG" ]; then
+    echo "$CONFIG not found"
+    exit 1
+fi
+
+source $CONFIG
 
 RAW_DATA="$(intel_reg read ${REGISTER})"
 CYCLE="${RAW_DATA:56:4}"
