adding script  for cleaning MyJD config, restructure scripts, adding simple checks for config, check for tty

diff --git a/JDownloaderHeadless b/JDownloaderHeadless
--- a/JDownloaderHeadless
+++ b/JDownloaderHeadless
@@ -1,30 +1,44 @@
 #!/usr/bin/env bash
-if [ "$(id -u)" -eq "0" ]; then
-  #restart as user jdownloader
-  echo "changing to user \"jdownloader\""
-  runuser jdownloader -c "/bin/bash $0 $@" -s /bin/bash
-  exit $?
-fi
-groups | grep -q -E '(\s|^)jdownloader(\s|$)' >/dev/null
-if [ "$?" -eq  0 ]; then
-  echo "Starting global JDownloader"
-  umask u=rwx,g=rwx,o=rx
-  cd '/opt/JDownloader'
-else
-  echo "starting local JDownloader"
-  mkdir -p "${HOME}/.jd"
-	cd "${HOME}/.jd"
+THIS_PATH="$(dirname "$(readlink -f "$0")")"
+source "$THIS_PATH/changeUser"
+
+
+function showFailure(){
+  local FAILURE="$1"
+  if [ -t 0 ] ; then
+    echo "WARNING: $FAILURE"
+  else
+    echo "ERROR: $FAILURE"
+    echo "You could run \"JDownloaderHeadlessCleanLogin\" to remove entire MyJDownloader Settings."
+    echo "Afterwards you should run \"JDownloaderHeadless\" in a terminal"
+    exit 2
+  fi
+}
+
+#check for config
+if [ ! -f "cfg/org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json" ]; then
+  showFailure "Configurationfile not set"
 fi
 
-if [ ! -f "JDownloader.jar" ]; then
-	wget -O JDownloader.jar http://installer.jdownloader.org/JDownloader.jar
+
+grep email "cfg/org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json" >/dev/null
+if [ $? -ne 0 ]; then
+   showFailure "Email seems not to be set"
+fi
+
+grep password "cfg/org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json" >/dev/null
+if [ $? -ne 0 ]; then
+   showFailure "Password seems not to be set"
 fi
 
 LOGFILE="JDownloader.service.log"
-
-if [ -f "$LOGFILE" ]; then
-  # Save the old Logfile (this automatically removes the n-2 one, if there is one)
-  mv "${LOGFILE}" "${LOGFILE}.old"
-fi 
-echo "All output is redirected to \"$(readlink -f "${LOGFILE}")\"" 
-exec java -Djava.awt.headless=true -jar JDownloader.jar -norestart "$@" >"${LOGFILE}" 2>&1
+if [ -t 0 ] ; then
+  exec java -Djava.awt.headless=true -jar JDownloader.jar -norestart "$@"
+else
+  if [ -f "$LOGFILE" ]; then
+    # Save the old Logfile (this automatically removes the n-2 one, if there is one)
+    mv "${LOGFILE}" "${LOGFILE}.old"
+  fi 
+  echo "All output is redirected to \"$(readlink -f "${LOGFILE}")\"" 
+  exec java -Djava.awt.headless=true -jar JDownloader.jar -norestart "$@" >"${LOGFILE}" 2>&1
+fi
