attempt to fix the "agent already running" error from mkinitcpio-sign-install

diff --git a/mkinitcpio-sign-install b/mkinitcpio-sign-install
--- a/mkinitcpio-sign-install
+++ b/mkinitcpio-sign-install
@@ -1,14 +1,14 @@
 #!/bin/bash -e
 
 pushd /usr/lib/initcpio/sign
-gpg-agent --daemon --max-cache-ttl 1
+gpg-connect-agent --homedir . reloadagent /bye
 keys=(`gpg --homedir . --list-keys --with-colons | awk -F: '/^pub:/ { print $5 }' | tr '\n' ' '`)
 
 if [[ $keys != "" ]]; then
   echo "found $keys"
 else
   gpg --homedir . --gen-key
-  [ $? -ne 0 ] && 1>&2 echo "you need to generate a GPG keypair to use for signing in /usr/lib/initcpio/sign" && exit 1
+  [ $? -ne 0 ] && 1>&2 echo "failed to generate a GPG keypair in /usr/lib/initcpio/sign" && exit 1
   gpg --homedir . --export > ~/boot.key
 fi
 
