2022.3

diff --git a/mullvad-vpn.install b/mullvad-vpn.install
--- a/mullvad-vpn.install
+++ b/mullvad-vpn.install
@@ -1,11 +1,14 @@
 pre_install() {
   if systemctl status mullvad-daemon &> /dev/null; then
     echo 'Stopping & disabling Mullvad VPN daemon...'
-    /opt/mullvad-vpn-cli/resources/mullvad-setup prepare-restart || true
+    /opt/mullvad-cli/resources/mullvad-setup prepare-restart || true
     systemctl disable --now mullvad-daemon
+    cp /var/log/mullvad-vpn/daemon.log /var/log/mullvad-vpn/old-install-daemon.log \
+      || echo "Failed to copy old daemon log"
   fi
 
-  rm -f /var/cache/mullvad-vpn/relays.json || true
+  rm -f /var/cache/mullvad-vpn/relays.json
+  rm -f /var/cache/mullvad-vpn/api-ip-address.txt
 }
 
 post_install() {
@@ -28,14 +31,13 @@ post_upgrade() {
 }
 
 pre_remove() {
-  /usr/bin/mullvad account clear-history || echo "Failed to remove leftover WireGuard keys"
-
   # the user might've disabled or stopped the service themselves already
   echo 'Making sure the Mullvad VPN daemon is stopped & disabled...'
   systemctl stop mullvad-daemon || true
   systemctl disable mullvad-daemon || true
 
-  /opt/mullvad-vpn-cli/resources/mullvad-setup reset-firewall || true
+  /opt/mullvad-cli/resources/mullvad-setup reset-firewall || echo "Failed to reset firewall"
+  /opt/mullvad-cli/resources/mullvad-setup remove-device || echo "Failed to remove device from account"
 }
 
 post_remove() {
