2020.6

diff --git a/mullvad-vpn.install b/mullvad-vpn.install
--- a/mullvad-vpn.install
+++ b/mullvad-vpn.install
@@ -5,14 +5,16 @@ pre_install() {
 		systemctl disable --now mullvad-daemon
 	fi
 
+	pkill -x "mullvad-gui" || true
+
 	rm -f /var/cache/mullvad-vpn/relays.json || true
 }
 
 post_install() {
+	chmod u+s "/usr/bin/mullvad-exclude"
+
 	echo 'Enabling Mullvad VPN daemon...'
 	systemctl enable --now mullvad-daemon
-
-	chmod u+s "/usr/bin/mullvad-exclude"
 }
 
 pre_upgrade() {
@@ -28,10 +30,14 @@ post_upgrade() {
 }
 
 pre_remove() {
+	/usr/bin/mullvad account clear-history || echo "Failed to remove leftover WireGuard keys"
+
 	# the user might've disabled or stopped the service themselves already
 	echo 'Making sure the Mullvad VPN daemon is stopped & disabled...'
 	systemctl stop mullvad-daemon || true
 	systemctl disable mullvad-daemon || true
+
+	/opt/Mullvad\ VPN/resources/mullvad-setup reset-firewall || true
 }
 
 post_remove() {
