2020.6

diff --git a/mullvad-vpn-cli.install b/mullvad-vpn-cli.install
--- a/mullvad-vpn-cli.install
+++ b/mullvad-vpn-cli.install
@@ -12,9 +12,9 @@ post_install() {
             /etc/mullvad-vpn/settings.json
         echo 'Please edit /etc/mullvad-vpn/settings.json'
     fi
+    chmod u+s "/usr/bin/mullvad-exclude"
 	echo 'Enabling Mullvad VPN daemon...'
 	systemctl enable mullvad-daemon
-    chmod u+s "/usr/bin/mullvad-exclude"
     echo -----------------------------------------------------------------------------------
     echo 'Mullvad daemon enabled but not started because the CLI might be used remotely.'
     echo 'Be aware that the daemon will be started after a reboot.'
@@ -30,17 +30,21 @@ pre_upgrade() {
 }
 
 post_upgrade() {
+    chmod u+s "/usr/bin/mullvad-exclude"
     echo 'Restarting Mullvad VPN daemon...'
     systemctl daemon-reload
     systemctl start mullvad-daemon
-    chmod u+s "/usr/bin/mullvad-exclude"
 }
 
 pre_remove() {
+    /usr/bin/mullvad account clear-history || echo "Failed to remove leftover WireGuard keys"
+
     # the user might've disabled or stopped the service themselves already
     echo 'Making sure the Mullvad VPN daemon is stopped & disabled...'
     systemctl stop mullvad-daemon || true
     systemctl disable mullvad-daemon || true
+
+    /opt/mullvad-vpn-cli/mullvad-setup reset-firewall || true
 }
 
 post_remove() {
