bug fixes, legacy_pty support

diff --git a/nconfig-wrapper b/nconfig-wrapper
--- a/nconfig-wrapper
+++ b/nconfig-wrapper
@@ -1,8 +1,9 @@
 #!/bin/bash
-[ -a ./package-this ] || {
+[ -a ./nconfig-wrapper ] || {
     echo "You have to run this from the same directory!"
     exit 1
 }
+croak()        { echo "ERROR: $@"; exit; }
 [ -f /etc/bash.functions ] && . /etc/bash.functions
 [ -f /usr/share/ppz/bash.functions ] && . /usr/share/ppz/bash.functions
 [ "$1" ] && REPO="$1" || croak USAGE: ./package-this [repo-directory]
@@ -29,9 +30,13 @@ askyn "update package?" && {
 	 sed -i 's/^[#]*\s*\(return\s*1\)$/#  \1/ig' PKGBUILD
 	 makepkg -oecd
 	 makepkg -cd
-	 PF=$(ls -1tr *.pkg.tar.xz | tail -n 1)
-	 mv $PF ${REPO}
-	 repo-add ${REPO}/hir.db.tar.gz ${REPO}/$PF
+	 PF=$(ls -1Atr linux-linode-*.pkg.tar.xz | tail -n 1)
+	 mv "${PF}" "${REPO}"/
+	 repo-add "${REPO}"/hir.db.tar.gz "${REPO}/${PF}"
+	 IFS=$'\n'
+	 for file in $(ls -1Atr "${REPO}"/linux-linode-*.pkg.tar.xz | head -n -1); do
+		  rm -i "$file"
+	 done
 } || {
 	 sed -i 's/^[#]*\s*\(return\s*1\)$/#  \1/ig' PKGBUILD
 	 makepkg -oecd
