Import from pkgbuild.com service

diff --git a/pacman-uncage b/pacman-uncage
--- a/pacman-uncage
+++ b/pacman-uncage
@@ -21,54 +21,54 @@
 #   USA. 
 # 
 
-myver='2.9.8' 
+myver='2.9.8.3'
 dbroot="/var/lib/pacman" 
 tmproot="/var/lib/pacman.new" 
 pacmandb="/var/lib/pacman.db" 
 pacmanlog=$(pacman -Qv | grep "Log File" | cut -d ":" -f2)
 
 usage() { 
-        echo "pacman-uncage $myver" 
-        echo "usage: $0 [pacman_db_root]" 
-        echo 
-        echo "pacman-uncage returns your pacman db to the generic style." 
-        echo 
+    echo "pacman-uncage $myver" 
+    echo "usage: $0 [pacman_db_root]" 
+    echo 
+    echo "pacman-uncage returns your pacman db to the generic style." 
+    echo 
 } 
 
 die() { 
-        echo "pacman-uncage: $*" >&2 
-        exit 1 
+    echo "pacman-uncage: $*" >&2 
+    exit 1 
 } 
 
 die_r() { 
-        rm -f /tmp/pacman.lck 
-        die $* 
+    rm -f /tmp/pacman.lck 
+    die $* 
 } 
 
 if [ "$1" != "" ]; then 
-        if [ "$1" = "-h" -o "$1" = "--help" ]; then 
-                usage 
-                exit 0 
-        fi 
-        dbroot=$1 
+    if [ "$1" = "-h" -o "$1" = "--help" ]; then 
+        usage 
+        exit 0 
+    fi 
+    dbroot=$1 
 fi 
 
-if [ "`id -u`" != 0 ]; then 
-        die "You must be root to uncage the database" 
+if [ $(id -u) != 0 ]; then 
+    die "You must be root to uncage the database" 
 fi
 
 # added by wain: make sure pacmandb is mounted
 if ! mount -l | grep $dbroot >/dev/null; then
-	die "Pacmandb must be mounted"
+    die "Pacmandb must be mounted"
 fi
 
 # make sure pacman isn't running 
 if [ -f /tmp/pacman.lck ]; then 
-        die "Pacman lockfile was found.  Cannot run while pacman is running." 
+    die "Pacman lockfile was found.  Cannot run while pacman is running." 
 fi 
 
 if [ ! -d $dbroot ]; then 
-        die "$dbroot does not exist or is not a directory" 
+    die "$dbroot does not exist or is not a directory" 
 fi 
 
 # don't let pacman run while we do this 
@@ -96,19 +96,19 @@ find $dbroot -type f | sort | xargs md5sum >/tmp/pacsums.new
 echo "==> checking integrity..." 
 diff /tmp/pacsums.old /tmp/pacsums.new >/dev/null 2>&1 
 if [ $? -ne 0 ]; then 
-        # failed, move the old one back into place 
-        rm -rf $dbroot 
-        mkdir $dbroot 
-        mount -o loop $pacmandb $dbroot 
-        echo "[ $(date "+%Y-%m-%d %H:%M ")] Pacman-cage [cmd] >> Something went wrong. $pacmandb remounted to $dbroot." >> ${pacmanlog}
-        die_r "integrity check FAILED, reverting to old database" 
+    # failed, move the old one back into place 
+    rm -rf $dbroot 
+    mkdir $dbroot 
+    mount -o loop $pacmandb $dbroot 
+    echo "[ $(date "+%Y-%m-%d %H:%M ")] Pacman-cage [cmd] >> Something went wrong. $pacmandb remounted to $dbroot." >> ${pacmanlog}
+    die_r "integrity check FAILED, reverting to old database" 
 fi 
 
 echo "==> Removing old pacman.db" 
 rm $pacmandb 
 
 rm -f /tmp/pacman.lck /tmp/pacsums.old /tmp/pacsums.new 
-            
+
 echo "[ $(date "+%Y-%m-%d %H:%M ")] Pacman-cage [cmd] >> Pacman database has been uncaged." >> ${pacmanlog}
 echo 
 echo "Finished.  Your pacman database has been uncaged!. Welcome home." 
