Prevent manual user intervention

diff --git a/php-cs-fixer.install b/php-cs-fixer.install
--- a/php-cs-fixer.install
+++ b/php-cs-fixer.install
@@ -1,8 +1,12 @@
 post_install() {
-  echo
-  echo "Warning: If you previously changed phar.readonly = Off you may now set phar.readonly = On in your php.ini";
+  if ! php -i | grep 'PHP Archive support => enabled' >/dev/null 2>&1; then
+    echo
+    echo "Error: phar.so must be enabled in your php.ini"
+		echo
+    exit 1
+  fi
 }
 
 post_upgrade() {
-	post_install
+  post_install
 }
