Add new options: --google-dns: Use Google's DNS service --restore-dns: Restore the original /etc/resolv.conf file

diff --git a/pia-tools b/pia-tools
--- a/pia-tools
+++ b/pia-tools
@@ -21,7 +21,7 @@ function usage() {
     echo "-r: Refresh (request port forwarding again) [default]"
     echo "-a: Block non VPN traffic (iptables)"
     echo "-d: Unblock non VPN traffic (iptables) [default]"
-    echo "-g: Use Google DNS (updates resolv.conf)"
+    echo "-g: Use PIA DNS (updates resolv.conf)"
     echo "-u: Update configuration files" 
     echo "-c: Ensure OpenVPN is running. If not stop transmissiond"
     echo "-h: Display this message"
@@ -207,9 +207,30 @@ function iplist_unblock() {
     echo 'Done !'
 }
 
+function _dns() {
+    mv /etc/resolv.conf /etc/resolv.conf.orig
+    echo -n "Updating resolv.conf file... "
+    echo "# Generated by pia-tools" > /etc/resolv.conf
+    for dns in $@; do
+        echo "nameserver $dns" >> /etc/resolv.conf
+    done
+    echo 'Done!'
+}
+
 function pia_dns() {
-    echo -n "Updating resolv.conf file..."
-    echo -e "# Generated by pia-tools\nnameserver 4.2.2.1\nnameserver 4.2.2.2" > /etc/resolv.conf   
+    _dns '4.2.2.1' '4.2.2.2'
+}
+
+function google_dns() {
+    _dns '8.8.8.8' '8.8.4.4'
+}
+
+function restore_dns() {
+    if [[ ! -f /etc/resolv.conf.orig ]]; then
+        echo "Could not find a resolv.conf.bak" >&2
+        return 1
+    fi
+    mv -f /etc/resolv.conf.orig /etc/resolv.conf
 }
 
 check_root "$*" # check permissions
@@ -221,7 +242,7 @@ if [[ $# -eq 0 ]] || [[ $# -gt 5 ]]; then
     #ip_action=disallow
 fi  
 
-while getopts ':adgprciuh-' OPTION ; do
+while getopts ':adgprciuh-' OPTION; do
     case "$OPTION" in
         a)
             test $ip_action && exit 1
@@ -240,7 +261,7 @@ while getopts ':adgprciuh-' OPTION ; do
             port_action=refresh
             ;;
         g)
-            pdns=pdns
+            dns=pia
             ;;
         u)
             update=update
@@ -274,7 +295,13 @@ while getopts ':adgprciuh-' OPTION ; do
                     ip_action=disallow
                     ;;
                 --pia-dns)
-                    pdns=pdns
+                    dns=pia
+                    ;;
+                --google-dns)
+                    dns=google
+                    ;;
+                --restore-dns)
+                    dns=restore
                     ;;
                 --update)
                     update=update
@@ -317,6 +344,11 @@ fi
 
 [[ -n "$check" ]] && check_ovpn
 [[ -n "$info" ]] && info
-[[ -n "$pdns" ]] && pia_dns
+
+case "$dns" in
+    google) google_dns ;;
+    restore) restore_dns ;;
+    pia) pia_dns ;;
+esac
 
 exit 0
