Fix broken setup and wrong service state detection

diff --git a/pia-tools b/pia-tools
--- a/pia-tools
+++ b/pia-tools
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Description: Script to automate privateinternetacces port forwarding and 
 # starting/stopping transmission when connected/disconnected and other stuff
-# Version: 0.9.4
+# Version: 0.9.5
 # Author: Philipp Schmitt (philipp<at>schmitt.co)
 # Documentation: cf. pia-tools.groff
 # Sources: iptables -> https://www.privateinternetaccess.com/forum/index.php?p=/discussion/35/block-non-vpn-traffic-on-linux-with-iptables-protect-against-disconnect/p1
@@ -75,7 +75,7 @@ function check_transmission() {
 
 # Checks if the OpenVPN service is running
 function check_ovpn() {
-    local ovpnd="$(systemctl -t service | grep 'openvpn@.* active')"
+    local ovpnd="$(systemctl -t service | grep 'pia@.* active')"
     if [[ -z "$ovpnd" ]]; then
         echo 'OpenVPN service not running !' >&2
         if check_transmission; then
@@ -91,7 +91,7 @@ function check_ovpn() {
 }
 
 function info() {
-    local vpn_exit="$(systemctl -t service | grep 'openvpn@.* active' \
+    local vpn_exit="$(systemctl -t service | grep 'pia@.* active' \
                     | awk '{ print $NF }')"
     if check_ovpn; then
         echo "OpenVPN is running (Exit point: $vpn_exit)"
@@ -317,7 +317,7 @@ function google_dns() {
 
 function restore_dns() {
     if [[ ! -f /etc/resolv.conf.orig ]]; then
-        echo "Could not find a resolv.conf.bak" >&2
+        echo "Could not find a resolv.conf.orig" >&2
         return 1
     fi
     mv -f /etc/resolv.conf.orig /etc/resolv.conf
@@ -327,43 +327,46 @@ function restore_dns() {
 # When started by OpenVPN daemon (up script) this script gets called like this:
 # $0 tun0 1500 1542 10.185.1.6 10.185.1.5 init
 if [[ $# -eq 0 ]] || [[ $# -gt 5 ]]; then
-    port_action=refresh
-    #ip_action=disallow
+    action_port=refresh
+    #action_fw=disallow
 fi
+
+# Every function except help needs root permissions
+check_root "$*"
 
 while getopts ':adgprciuhsv-' OPTION; do
     case "$OPTION" in
         a)
-            test $ip_action && exit 1
-            ip_action=allow
+            test $action_fw && exit 1
+            action_fw=allow
             ;;
         d)
-            test $ip_action && exit 1
-            ip_action=disallow
+            test $action_fw && exit 1
+            action_fw=disallow
             ;;
         p)
-            test $port_action && exit 1
-            port_action=portfwd
+            test $action_port && exit 1
+            action_port=portfwd
             ;;
         r)
-            test $port_action && exit 1
-            port_action=refresh
+            test $action_port && exit 1
+            action_port=refresh
             ;;
         g)
             test $dns && exit 1
-            dns_action=pia
+            action_dns=pia
             ;;
         u)
-            update=update
+            action_update=1
             ;;
         s)
-            setup=1
+            action_setup=1
             ;;
         c)
-            check=check
+            action_check=1
             ;;
         i)
-            info=info
+            action_info=1
             ;;
         h)
             action_help=1
@@ -378,44 +381,44 @@ while getopts ':adgprciuhsv-' OPTION; do
             OPTION=$(echo $OPTION | cut -d'=' -f1)
             case $OPTION in
                 --port)
-                    test $port_action && exit 1
-                    port_action=portfwd
+                    test $action_port && exit 1
+                    action_port=portfwd
                     ;;
                 --refresh)
-                    test $port_action && exit 1
-                    port_action=refresh
+                    test $action_port && exit 1
+                    action_port=refresh
                     ;;
                 --allow)
-                    test $ip_action && exit 1
-                    ip_action=allow
+                    test $action_fw && exit 1
+                    action_fw=allow
                     ;;
                 --disallow)
-                    test $ip_action && exit 1
-                    ip_action=disallow
+                    test $action_fw && exit 1
+                    action_fw=disallow
                     ;;
                 --pia-dns)
                     test $dns && exit 1
-                    dns_action=pia
+                    action_dns=pia
                     ;;
                 --google-dns)
                     test $dns && exit 1
-                    dns_action=google
+                    action_dns=google
                     ;;
                 --restore-dns)
                     test $dns && exit 1
-                    dns_action=restore
+                    action_dns=restore
                     ;;
                 --update)
-                    update=update
+                    action_update=1
                     ;;
                 --setup)
-                    setup=1
+                    action_setup=1
                     ;;
                 --check)
-                    check=check
+                    action_check=1
                     ;;
                 --info)
-                    info=info
+                    action_info=1
                     ;;
                 --help)
                     action_help=1 
@@ -423,9 +426,6 @@ while getopts ':adgprciuhsv-' OPTION; do
                 --verbose)
                     VERBOSE=1
                     ;;
-                #--debug)
-                # TODO
-                #    ;;
                 *)
                     action_help=1 
                     ;;
@@ -440,31 +440,29 @@ while getopts ':adgprciuhsv-' OPTION; do
 done
 
 test $action_help && { usage $(basename $0); exit $?; }
-# Every function except help needs root permissions
-check_root "$*" # check permissions
-test $info && { info; exit $?; }
-test $setup && { setup; exit $?; }
-test $update && update_config
-test $check && check_ovpn
+test $action_info && { info; exit $?; }
+test $action_setup && { setup; exit $?; }
+test $action_update && update_config
+test $action_check && check_ovpn
 
-# Request port forwarding if port_action is set or no other action is
-if test "$port_action" || ! test $port_action $dns_action $ip_action $check $info $update; then
+# Request port forwarding if action_port is set or no other action is
+if test "$action_port" || ! test $action_port $action_dns $action_fw $action_check $action_info $action_update $action_setup; then
     client_id=$(cat $PIA_CLIENT_ID_FILE)
-    if [[ -z "$client_id" ]] || [[ "$port_action" == "portfwd" ]]; then
+    if [[ -z "$client_id" ]] || [[ "$action_port" == "portfwd" ]]; then
         client_id=$(new_client_id)
     fi
     check_ovpn
     request_port $client_id
-    unset client_id port_action
+    unset client_id action_port
 fi
 
 # Block/Unblock non-VPN traffic if requested
-case "$ip_action" in
+case "$action_fw" in
     disallow) iplist_block ;;
     allow) iplist_unblock ;;
 esac
 
-case "$dns_action" in
+case "$action_dns" in
     google) google_dns ;;
     restore) restore_dns ;;
     pia) pia_dns ;;
