Version 7.3-GE-1

diff --git a/proton-sanitize_makefile.patch b/proton-sanitize_makefile.patch
--- a/proton-sanitize_makefile.patch
+++ b/proton-sanitize_makefile.patch
@@ -1,16 +1,16 @@
-diff --git a/build/makefile_base.mak b/build/makefile_base.mak
-index dc52210f..dcfca71c 100755
---- a/build/makefile_base.mak
-+++ b/build/makefile_base.mak
-@@ -62,7 +62,6 @@ ifeq ($(ENABLE_CCACHE),1)
+diff --git a/Makefile.in b/Makefile.in
+index 8eb74e70..11b4f7c7 100644
+--- a/Makefile.in
++++ b/Makefile.in
+@@ -63,7 +63,6 @@ ifeq ($(ENABLE_CCACHE),1)
  	export CCACHE_DIR := $(if $(CCACHE_DIR),$(CCACHE_DIR),$(HOME)/.ccache)
- 	DOCKER_OPTS := -v $(CCACHE_DIR):$(CCACHE_DIR)$(CONTAINER_MOUNT_OPTS) $(CCACHE_ENV) -e CCACHE_DIR=$(CCACHE_DIR) $(DOCKER_OPTS)
+ 	override DOCKER_OPTS := -v $(CCACHE_DIR):$(CCACHE_DIR)$(CONTAINER_MOUNT_OPTS) $(CCACHE_ENV) -e CCACHE_DIR=$(CCACHE_DIR) $(DOCKER_OPTS)
  else
 -	export CCACHE_DISABLE := 1
- 	DOCKER_OPTS := $(CCACHE_ENV) -e CCACHE_DISABLE=1 $(DOCKER_OPTS)
+ 	override DOCKER_OPTS := $(CCACHE_ENV) -e CCACHE_DISABLE=1 $(DOCKER_OPTS)
  endif
  
-@@ -120,7 +119,7 @@ container-build:
+@@ -121,7 +120,7 @@ container-build:
  all32 $(MAKECMDGOALS32): container-build
  all64 $(MAKECMDGOALS64): container-build
  else
@@ -19,7 +19,7 @@ index dc52210f..dcfca71c 100755
  endif
  
  
-@@ -170,11 +169,12 @@ else
+@@ -171,11 +170,12 @@ else
  endif
  
  CROSSLDFLAGS   += -Wl,--file-alignment,4096
@@ -34,10 +34,10 @@ index dc52210f..dcfca71c 100755
  CARGO_BUILD_ARG := --release
  
  ##
-@@ -359,8 +359,8 @@ ALL_TARGETS += dist
+@@ -369,8 +369,8 @@ ALL_TARGETS += dist
  GOAL_TARGETS += dist
  
- dist_prefix: wine gst_good
+ dist_prefix: wine gst_good gst_libav gst_plugins_rs
 -	find $(DST_LIBDIR32)/wine -type f -execdir chmod a-w '{}' '+'
 -	find $(DST_LIBDIR64)/wine -type f -execdir chmod a-w '{}' '+'
 +	find $(DST_LIBDIR32)/wine -type f -execdir chmod go-w '{}' '+'
@@ -45,7 +45,7 @@ index dc52210f..dcfca71c 100755
  	rm -rf $(abspath $(DIST_PREFIX))
  	python3 $(SRCDIR)/default_pfx.py $(abspath $(DIST_PREFIX)) $(abspath $(DST_DIR)) $(STEAM_RUNTIME_RUNSH)
  
-@@ -413,6 +413,9 @@ endif # ifeq ($(CONTAINER),)
+@@ -451,11 +451,15 @@ $(eval $(call rules-meson,dav1d,64))
  ##
  
  GST_COMMON_MESON_ARGS := \
@@ -55,73 +55,65 @@ index dc52210f..dcfca71c 100755
  	-Dexamples=disabled \
  	-Dtests=disabled \
  	-Dgtk_doc=disabled \
-@@ -425,6 +428,7 @@ GST_COMMON_MESON_ARGS := \
- 
- GST_ORC_MESON_ARGS := \
- 	-Dorc-test=disabled \
-+	-Dpackage-name="GStreamer Orc (Proton)" \
- 	$(GST_COMMON_MESON_ARGS)
- 
- $(eval $(call rules-source,gst_orc,$(SRCDIR)/gst-orc))
-@@ -441,6 +445,9 @@ GSTREAMER_MESON_ARGS := \
+ 	-Dintrospection=disabled \
+ 	-Dgobject-cast-checks=disabled \
++	-Dorc=enabled \
+ 	-Dglib-asserts=disabled \
+ 	-Dglib-checks=disabled \
+ 	-Dnls=disabled \
+@@ -479,6 +483,8 @@ GSTREAMER_MESON_ARGS := \
  	-Dbenchmarks=disabled \
  	-Dtools=disabled \
  	-Dbash-completion=disabled \
 +	-Dptp-helper-permissions=capabilities \
 +	-Ddbghelp=disabled \
-+	-Dpackage-name="GStreamer (Proton)" \
  	$(GST_COMMON_MESON_ARGS)
  
  GSTREAMER_DEPENDS = gst_orc
-@@ -477,6 +484,8 @@ GST_BASE_MESON_ARGS := \
+@@ -515,6 +521,7 @@ GST_BASE_MESON_ARGS := \
  	-Dx11=disabled \
  	-Dxshm=disabled \
  	-Dxvideo=disabled \
 +	-Dtools=disabled \
-+	-Dpackage-name="GStreamer Base Plugins (Proton)" \
  	$(GST_COMMON_MESON_ARGS)
  
  GST_BASE_DEPENDS = gst_orc gstreamer
-@@ -540,7 +549,8 @@ GST_GOOD_MESON_ARGS := \
+@@ -578,7 +585,7 @@ GST_GOOD_MESON_ARGS := \
  	-Dwavenc=disabled \
  	-Dximagesrc=disabled \
  	-Dy4m=enabled \
 -	-Ddoc='disabled' \
 +	-Dtools=disabled \
-+	-Dpackage-name="GStreamer Good Plugins (Proton)" \
  	$(GST_COMMON_MESON_ARGS)
  
  GST_GOOD_DEPENDS = gst_orc gstreamer gst_base
-@@ -575,6 +585,9 @@ GST_BAD_MESON_ARGS := \
- 	-Dopencv=disabled \
- 	-Dvoamrwbenc=disabled \
- 	-Dx265=disabled \
-+	-Dopenexr=disabled \
-+	-Dtools=disabled \
-+	-Dpackage-name="GStreamer Bad Plugins (Proton)" \
- 	$(GST_COMMON_MESON_ARGS)
- 
- GST_BAD_DEPENDS = gst_orc gstreamer gst_base
-@@ -590,6 +603,8 @@ $(eval $(call rules-meson,gst_bad,64))
- 
- GST_UGLY_MESON_ARGS := \
-         -Ddoc='disabled' \
-+        -Dtools='disabled' \
-+        -Dpackage-name="GStreamer Ugly Plugins (Proton)" \
- 	$(GST_COMMON_MESON_ARGS)
- 
- GST_UGLY_DEPENDS = gst_orc gstreamer gst_base
-@@ -605,6 +620,9 @@ $(eval $(call rules-meson,gst_ugly,64))
+@@ -594,6 +601,8 @@ $(eval $(call rules-meson,gst_good,64))
  
  GST_LIBAV_MESON_ARGS := \
          -Ddoc=disabled \
 +        -Dtools=disabled \
 +        --force-fallback-for=FFmpeg \
-+        -Dpackage-name="GStreamer FFmpeg Plugin (Proton)" \
- 	$(GST_COMMON_MESON_ARGS)
+     $(GST_COMMON_MESON_ARGS)
  
  GST_LIBAV_DEPENDS = gst_orc gstreamer gst_base
-@@ -768,8 +786,14 @@ WINE_SOURCE_ARGS = \
+@@ -663,6 +672,8 @@ GST_BAD_MESON_ARGS := \
+ 	-Dvoamrwbenc=disabled \
+ 	-Dnvcodec=disabled \
+ 	-Dx265=disabled \
++	-Dopenexr=disabled \
++	-Dtools=disabled \
+ 	$(GST_COMMON_MESON_ARGS)
+ 
+ GST_BAD_DEPENDS = gst_orc gstreamer gst_base
+@@ -677,6 +688,7 @@ $(eval $(call rules-meson,gst_bad,64))
+ 
+ GST_UGLY_MESON_ARGS := \
+         -Ddoc='disabled' \
++        -Dtools='disabled' \
+ 	$(GST_COMMON_MESON_ARGS)
+ 
+ GST_UGLY_DEPENDS = gst_orc gstreamer gst_base
+@@ -808,7 +820,13 @@ WINE_SOURCE_ARGS = \
    --exclude include/config.h.in \
  
  WINE_CONFIGURE_ARGS = \
@@ -129,31 +121,13 @@ index dc52210f..dcfca71c 100755
 +  --with-gstreamer \
 +  --with-faudio \
    --with-mingw \
-   --without-xpresent \
 +  --without-vkd3d \
 +  --without-oss \
 +  --disable-win16 \
    --disable-tests
  
  WINE_CONFIGURE_ARGS64 = --enable-win64
-@@ -824,16 +848,6 @@ $(OBJ)/.vrclient-post-source:
- 	mkdir -p $(VRCLIENT_OBJ64) && cp -a $(VRCLIENT_SRC)/vrclient_x64/vrclient_x64.spec $(VRCLIENT_OBJ64)/vrclient_x64.spec
- 	touch $@
- 
--##
--## xkbcommon -- needed for wayland support in wome
--##
--
--XKBCOMMON_MESON_ARGS := \
--        -Denable-docs='false'
--
--$(eval $(call rules-source,xkbcommon,$(SRCDIR)/xkbcommon))
--$(eval $(call rules-meson,xkbcommon,32))
--$(eval $(call rules-meson,xkbcommon,64))
- 
- 
- ##
-@@ -843,6 +857,9 @@ $(eval $(call rules-meson,xkbcommon,64))
+@@ -871,6 +889,9 @@ $(OBJ)/.vrclient-post-source:
  DXVK_MESON_ARGS32 = --bindir=$(DXVK_DST32)/lib/wine/dxvk
  DXVK_MESON_ARGS64 = --bindir=$(DXVK_DST64)/lib64/wine/dxvk
  
@@ -163,7 +137,7 @@ index dc52210f..dcfca71c 100755
  $(eval $(call rules-source,dxvk,$(SRCDIR)/dxvk))
  $(eval $(call rules-meson,dxvk,32,CROSS))
  $(eval $(call rules-meson,dxvk,64,CROSS))
-@@ -865,6 +882,9 @@ $(OBJ)/.dxvk-post-build32:
+@@ -893,6 +914,9 @@ $(OBJ)/.dxvk-post-build32:
  DXVK_NVAPI_MESON_ARGS32 = --bindir=$(DXVK_NVAPI_DST32)/lib/wine/nvapi
  DXVK_NVAPI_MESON_ARGS64 = --bindir=$(DXVK_NVAPI_DST64)/lib64/wine/nvapi
  
@@ -173,7 +147,7 @@ index dc52210f..dcfca71c 100755
  $(eval $(call rules-source,dxvk-nvapi,$(SRCDIR)/dxvk-nvapi))
  $(eval $(call rules-meson,dxvk-nvapi,32,CROSS))
  $(eval $(call rules-meson,dxvk-nvapi,64,CROSS))
-@@ -928,10 +948,13 @@ VKD3D_PROTON_SOURCE_ARGS = \
+@@ -956,10 +980,13 @@ VKD3D_PROTON_SOURCE_ARGS = \
    --exclude vkd3d_build.h.in \
    --exclude vkd3d_version.h.in \
  
@@ -188,6 +162,26 @@ index dc52210f..dcfca71c 100755
  $(eval $(call rules-source,vkd3d-proton,$(SRCDIR)/vkd3d-proton))
  $(eval $(call rules-meson,vkd3d-proton,32,CROSS))
  $(eval $(call rules-meson,vkd3d-proton,64,CROSS))
+diff --git a/configure.sh b/configure.sh
+index 48d6004e..33eb9f3d 100755
+--- a/configure.sh
++++ b/configure.sh
+@@ -141,6 +141,7 @@ function configure() {
+     CONTAINER_MOUNT_OPTS=:Z
+   fi
+ 
++  if [ "$arg_container_engine" != "none" ]; then
+   if [[ -n "$arg_container_engine" ]]; then
+     check_container_engine "$arg_container_engine" || die "Specified container engine \"$arg_container_engine\" doesn't work"
+   else
+@@ -153,6 +154,7 @@ function configure() {
+         die "${arg_container_engine:-Container engine discovery} has failed. Please fix your setup."
+     fi
+   fi
++  fi
+ 
+   stat "Using $arg_container_engine."
+ 
 diff --git a/make/rules-autoconf.mk b/make/rules-autoconf.mk
 index 0827caa9..4e6d19f2 100644
 --- a/make/rules-autoconf.mk
@@ -205,22 +199,23 @@ index 0827caa9..4e6d19f2 100644
  endif
  endef
 diff --git a/make/rules-cargo.mk b/make/rules-cargo.mk
-index 2dbfe75f..6afbc42c 100644
+index b2af34ca..c132fffb 100644
 --- a/make/rules-cargo.mk
 +++ b/make/rules-cargo.mk
-@@ -14,7 +14,9 @@ $$(OBJ)/.$(1)-configure$(3):
+@@ -14,8 +14,10 @@ $$(OBJ)/.$(1)-configure$(3):
  $$(OBJ)/.$(1)-build$(3):
  	@echo ":: building $(3)bit $(1)..." >&2
  	cd $$($(2)_SRC) && env $$($(2)_ENV$(3)) \
--	cargo build $$(filter -j%,$$(MAKEFLAGS)) --target "$$(CARGO_TARGET_$(3))" --target-dir $$($(2)_OBJ$(3)) $$(CARGO_BUILD_ARG)
 +	cargo update --offline --verbose
 +	cd $$($(2)_SRC) && env $$($(2)_ENV$(3)) \
-+	cargo build -j$$(SUBJOBS) --locked --offline --verbose --target "$$(CARGO_TARGET_$(3))" --target-dir $$($(2)_OBJ$(3)) $$(CARGO_BUILD_ARG)
- 	touch $$@
- endif
- endef
+ 	cargo build \
+-	      $$(filter -j%,$$(MAKEFLAGS)) \
++	      -j$$(SUBJOBS) --locked --offline --verbose \
+ 	      --target "$$(CARGO_TARGET_$(3))" \
+ 	      --target-dir $$($(2)_OBJ$(3)) \
+ 	      $$(CARGO_BUILD_ARG) \
 diff --git a/make/rules-cmake.mk b/make/rules-cmake.mk
-index 0e18df97..2150cba8 100644
+index c70751a2..1096dc19 100644
 --- a/make/rules-cmake.mk
 +++ b/make/rules-cmake.mk
 @@ -28,9 +28,9 @@ $$(OBJ)/.$(1)-configure$(3): $$($(2)_SRC)/CMakeLists.txt
@@ -236,10 +231,10 @@ index 0e18df97..2150cba8 100644
  endif
  endef
 diff --git a/make/rules-common.mk b/make/rules-common.mk
-index bc407604..c3a7dbeb 100644
+index ec083690..55978ca7 100644
 --- a/make/rules-common.mk
 +++ b/make/rules-common.mk
-@@ -125,8 +125,12 @@ $(2)_LIBFLAGS$(3) = $$(foreach d,$$($(2)_DEPS$(3)),-L$$($$(d)_LIBDIR$(3))) \
+@@ -119,8 +119,12 @@ $(2)_LIBFLAGS$(3) = $$(foreach d,$$($(2)_DEPS$(3)),-L$$($$(d)_LIBDIR$(3))) \
  # native version doesn't exist.
  
  $(2)_ENV$(3) = \
@@ -252,7 +247,7 @@ index bc407604..c3a7dbeb 100644
      CCACHE_BASEDIR="$$(CCACHE_BASEDIR)" \
      STRIP="$$(STRIP)" \
      AR="$$(TARGET_$(4)$(3))-ar" \
-@@ -140,7 +144,7 @@ $(2)_ENV$(3) = \
+@@ -134,7 +138,7 @@ $(2)_ENV$(3) = \
      PATH="$$(call list-join,:,$$(foreach d,$$($(2)_DEPS$(3)),$$($$(d)_BINDIR$(3))),,:):$$(SRC)/glslang/bin:$$$$PATH" \
      LD_LIBRARY_PATH="$$(call list-join,:,$$(foreach d,$$($(2)_DEPS$(3)),$$($$(d)_LIBDIR$(3))),,:)$$$$LD_LIBRARY_PATH" \
      PKG_CONFIG_PATH="$$(call list-join,:,$$(foreach d,$$($(2)_DEPS$(3)),$$($$(d)_LIBDIR$(3))/pkgconfig))" \
@@ -261,7 +256,7 @@ index bc407604..c3a7dbeb 100644
      CFLAGS="$$($(2)_INCFLAGS$(3)) $$($(2)_CFLAGS) $$(COMMON_FLAGS) $$(COMMON_FLAGS$(3))" \
      CPPFLAGS="$$($(2)_INCFLAGS$(3)) $$($(2)_CPPFLAGS) $$(COMMON_FLAGS) $$(COMMON_FLAGS$(3))" \
      CXXFLAGS="$$($(2)_INCFLAGS$(3)) $$($(2)_CXXFLAGS) $$(COMMON_FLAGS) $$(COMMON_FLAGS$(3)) -std=c++17" \
-@@ -164,7 +168,7 @@ $(2)_ENV$(3) += \
+@@ -158,7 +162,7 @@ $(2)_ENV$(3) += \
      CROSSCPPFLAGS="$$($(2)_INCFLAGS$(3)) $$($(2)_CPPFLAGS) $$(COMMON_FLAGS) $$(COMMON_FLAGS$(3))" \
      CROSSCXXFLAGS="$$($(2)_INCFLAGS$(3)) $$($(2)_CXXFLAGS) $$(COMMON_FLAGS) $$(COMMON_FLAGS$(3)) -std=c++17" \
      CROSSLDFLAGS="$$($(2)_LIBFLAGS$(3)) $$($(2)_LDFLAGS$(3)) $$($(2)_LDFLAGS) $$(CROSSLDFLAGS)" \
@@ -270,7 +265,7 @@ index bc407604..c3a7dbeb 100644
  
  endif
  
-@@ -177,14 +181,14 @@ else
+@@ -171,14 +175,14 @@ else
  install-strip = objcopy --file-alignment=4096 --strip-debug $(1) $(2)/$(notdir $(1)) && rm -f $(2)/$(notdir $(1)).debug
  endif
  
@@ -289,7 +284,23 @@ index bc407604..c3a7dbeb 100644
 +PKG_CONFIG_TARGET_CROSS32 := i686-w64-mingw32
  PKG_CONFIG_TARGET_CROSS64 := x86_64-w64-mingw32
  
- $(OBJ)/.%-post-build32:
+ LIBDIR_WINE_32 := wine/i386-unix
+diff --git a/make/rules-configure.mk b/make/rules-configure.mk
+index d04a3c53..18ac684e 100644
+--- a/make/rules-configure.mk
++++ b/make/rules-configure.mk
+@@ -26,9 +26,9 @@ $$(OBJ)/.$(1)-configure$(3):
+ $$(OBJ)/.$(1)-build$(3):
+ 	@echo ":: building $(3)bit $(1)..." >&2
+ 	cd "$$($(2)_OBJ$(3))" && env $$($(2)_ENV$(3)) \
+-	$$(MAKE)
++	$$(MAKE) -j$$(SUBJOBS)
+ 	cd "$$($(2)_OBJ$(3))" && env $$($(2)_ENV$(3)) \
+-	$$(MAKE) install
++	$$(MAKE) -j$$(SUBJOBS) install
+ 	touch $$@
+ endif
+ endef
 diff --git a/make/rules-meson.mk b/make/rules-meson.mk
 index d603bfde..f798edfc 100644
 --- a/make/rules-meson.mk
@@ -304,7 +315,7 @@ index d603bfde..f798edfc 100644
  endif
  endef
 diff --git a/make/rules-winemaker.mk b/make/rules-winemaker.mk
-index 25c4dd33..fb6ebc4d 100644
+index 69688a03..1c0d1d3b 100644
 --- a/make/rules-winemaker.mk
 +++ b/make/rules-winemaker.mk
 @@ -29,7 +29,7 @@ $$(OBJ)/.$(1)-build$(3):
@@ -314,5 +325,5 @@ index 25c4dd33..fb6ebc4d 100644
 -	$$(MAKE) -C "$$($(2)_OBJ$(3))" LIBRARIES="$$($(2)_LDFLAGS)"
 +	$$(MAKE) -j$$(SUBJOBS) -C "$$($(2)_OBJ$(3))" LIBRARIES="$$($(2)_LDFLAGS)"
  	cd "$$($(2)_OBJ$(3))" && touch "$(basename $(4)).spec" && env $$($(2)_ENV$(3)) \
- 	winebuild --dll --fake-module -E "$(basename $(4)).spec" -o "$(4).fake"
- ifeq ($(3),32)
+ 	winebuild --$(lastword $(subst ., ,$(4))) --fake-module -E "$(basename $(4)).spec" -o "$(4).fake"
+ 	mkdir -p $$($(2)_LIBDIR$(3))/$(LIBDIR_WINE_$(3))
