Package my own modifications to the script (which include coolreader18's and cleaning it up) and update pkgver

diff --git a/shitpost b/shitpost
--- a/shitpost
+++ b/shitpost
@@ -1,45 +1,41 @@
 #!/bin/bash
 
-#someone on /r/linuxmasterrace asked what image programs were good for shitposts
-#it got me thinking that there should be a cli command just for that
-#days later (I'm still pretty noob)...
+# someone on /r/linuxmasterrace asked what image programs were good for shitposts
+# it got me thinking that there should be a cli command just for that
+# days later (I'm still pretty noob)...
 
-#SHITPOST
-#Takes an image and adds some shitty text to it
+# Originally by Mykal Anderson
+# Patched by Declan Hoare 2016-12-02: use PNG instead of GIF for temp files to preserve quality
+# Modified by coolreader18 2021-03-01: fix some bugs and use a directory under /tmp for temporary files
+# Modified by Magnus Anderson 2021-09-21: clean up the code
 
-#   DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
-#       Version 2, December 2004 
-#Copyright (C) 2004 Sam Hocevar <sam@hocevar.net> 
-#Everyone is permitted to copy and distribute verbatim or modified 
-#copies of this license document, and changing it is allowed as long 
-#as the name is changed. 
-#   DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
-#TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND  MODIFICATION 
+# SHITPOST
+# Takes an image and adds some shitty text to it
+
+#   DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
+#            Version 2, December 2004
+# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
+# Everyone is permitted to copy and distribute verbatim or modified
+# copies of this license document, and changing it is allowed as long
+# as the name is changed.
+# DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
+# TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND  MODIFICATION
 # 0. You just DO WHAT THE FUCK YOU WANT TO.
 
-#Originally by Mykal Anderson
-
-# Patched by Declan Hoare 2016-12-02: use PNG instead of GIF for temp files to preserve quality
-
-#Begin
-
-#Check if imagemagick (just convert checked, but others used) is installed and exit if missing
-
+# Check if imagemagick (just convert checked, but others used) is installed and exit if missing
 command -v convert >/dev/null 2>&1 || { echo >&2 "I require ImageMagick but it's not installed.  Aborting."; exit 1; }
-
-#Get CLI args
-
-OPTIND=1
 
 top_text=" "
 bottom_text=" "
 image_file=""
+output_file=""
 
-while getopts "h?t:b:f:" opt; do
-
+# Get CLI args
+OPTIND=1
+while getopts "h?t:b:f:o:" opt; do
     case "$opt" in
     h|\?)
-        printf "Available options are:\n t - Top Text\n b - Bottom Text\n f - Path to image file - Mandatory!\n"
+        printf "Usage: shitpost -f /path/to/file [-t top -b bottom]\n\t-f\tPath to image file - Mandatory!\n\t-t\tTop Text\n\t-b\tBottom Text\n\t-o\tOutput file name\n"
         exit 0
         ;;
     t)  top_text="$OPTARG"
@@ -48,53 +44,44 @@ while getopts "h?t:b:f:" opt; do
         ;;
     f)  image_file="$OPTARG"
         ;;
+    o)  output_file="$OPTARG"
+        ;;
     esac
 done
 
+# Ensure that an image file is provided and exists. Does not check that it actually contains image data
+[[ -z "$image_file" ]] && echo "You must specify an image file. Use -h or -? for help." && exit 1
+
+# Let the user know any options that were invalid that were not already handled by getopts.
 shift $((OPTIND-1))
+[[ ! -z "$@" ]] && printf "Invalid argument(s): \"$@\"\nIgnored, continuing...\n"
 
-[ "$1" = "--" ] && shift
-
-#Make sure an image file was set and that it exists, or, what are we doing here, really. (Does not successfully check when source is a URL that fails to load, https for example) Would like to confirm it's an image file convert will take too but...
-if [ -z "$image_file" ]
-    then echo "You must specify an image file. Use -h or -? for help."; exit 1
-fi
-
-#Let the user know any options that were invalid that were not allready    handled by getopts.
-if [ ! -z "$@" ]
-    then printf "Invalid arguement(s): \"$@\"\nIgnored, continuing...\n"
-fi
-
-#Get some info on the file path etc
+# Get some info on the file path etc
 path=${image_file%/*} 
 base=${image_file##*/}
 fext=${base##*.}
 pref=${base%.*}
 
-#Upscale the image if it's too shitty. This is required to make the text readable as it's generated to fit the pixels of the original
-convert -resize 1024x1024\< "$image_file" shitpost-temp-resize.png
+# Set the output file to shitpost-INPUT_FILE if none was given
+[[ -z "$output_file" ]] && output_file="shitpost-$pref.$fext"
 
-#Get the height and width of the image to use later to size the overlays. Clipped height keeps things locked in the top and bottom fifth of the image.
-image_width=`identify -format "%[width]" shitpost-temp-resize.png`
-image_height=`identify -format "%[height]" shitpost-temp-resize.png`
+# Create a temporary directory to hold the temporary files
+tmpdir=$(mktemp -d)
+trap 'rm -rf "$tmpdir"' EXIT SIGINT
+
+# Upscale the image if it's too shitty. This is required to make the text readable as it's generated to fit the pixels of the original
+convert -resize 1024x1024\< "$image_file" "$tmpdir"/shitpost-temp-resize.png
+
+# Get the height and width of the image to use later to size the overlays. Clipped height keeps things locked in the top and bottom fifth of the image.
+image_width=$(identify -format "%[width]" "$tmpdir"/shitpost-temp-resize.png)
+image_height=$(identify -format "%[height]" "$tmpdir"/shitpost-temp-resize.png)
 clipped_height=$(($image_height/5))
 stroke_width=$(($clipped_height/40))
 
-
-convert -background none -fill white -stroke black -strokewidth "$stroke_width" -size "$image_width"x"$clipped_height" -gravity Center -font 'Impact' caption:"$top_text" temp-top-text.png
-convert -background none -fill white -stroke black -strokewidth "$stroke_width" -size "$image_width"x"$clipped_height" -gravity Center -font 'Impact' caption:"$bottom_text" temp-bottom-text.png
-composite -gravity north temp-top-text.png shitpost-temp-resize.png shitpost-temp-composite.png
-composite -gravity south temp-bottom-text.png shitpost-temp-composite.png shitpost-"$pref"."$fext"
-
-
-#Clean up
-rm temp-top-text.png
-rm temp-bottom-text.png
-rm shitpost-temp-resize.png
-rm shitpost-temp-composite.png
+convert -background none -fill white -stroke black -strokewidth "$stroke_width" -size "$image_width"x"$clipped_height" -gravity Center -font 'Impact' caption:"$top_text" "$tmpdir"/shitpost-temp-top-text.png
+convert -background none -fill white -stroke black -strokewidth "$stroke_width" -size "$image_width"x"$clipped_height" -gravity Center -font 'Impact' caption:"$bottom_text" "$tmpdir"/shitpost-temp-bottom-text.png
+composite -gravity north "$tmpdir"/shitpost-temp-top-text.png "$tmpdir"/shitpost-temp-resize.png "$tmpdir"/shitpost-temp-composite.png
+composite -gravity south "$tmpdir"/shitpost-temp-bottom-text.png "$tmpdir"/shitpost-temp-composite.png "$output_file"
 
 #Announce the results
-echo "Created file "$PWD"/shitpost-"$pref"."$fext""
-
-exit 0
-#End
+echo "Created file '$output_file'"
