remove bashism from dependency check

diff --git a/snooscraper b/snooscraper
--- a/snooscraper
+++ b/snooscraper
@@ -19,7 +19,7 @@
 
 #Error handling
 depends="sh curl jq sed grep find"
-for c in $depends; do if ! command -v "$c" >/dev/null 2>&1; then echo "Error: dependency ${c} is missing. Aborting."; exit 1; fi; done
+for c in $depends; do if ! command "$c" --help >/dev/null 2>&1; then echo "Error: dependency ${c} is missing. Aborting."; exit 1; fi; done
 if [ $# -gt 2 ]; then echo "Error: too many options. Aborting."; exit 1; fi
 if [ $# = 1 ] && [ ! "$1" = "-h" ] && [ ! "$1" = "--help" ]; then echo "Error: missing option. Aborting."; exit 1; fi
 trap 'echo "Interrupted, finishing early."; exit 1' INT
