Bump to v2.2.0.0108

diff --git a/sogou-autostart b/sogou-autostart
--- a/sogou-autostart
+++ b/sogou-autostart
@@ -4,8 +4,12 @@
 for i in $(seq 30); do
   if fcitx-remote &> /dev/null; then
     sogou-qimpanel
-    break
+    echo 'sogou-qimpanel started'
+    exit
   else
     sleep 1
   fi
 done
+
+echo 'sogou-qimpanel failed to start: fcitx not running'
+exit 1
