update

diff --git a/torhttp_hook b/torhttp_hook
--- a/torhttp_hook
+++ b/torhttp_hook
@@ -1,21 +1,17 @@
-#!/usr/bin/ash
-
+#!/bin/sh
 run_hook ()
 {
-	sysctl -w kernel.panic=20
+	mkdir -p /run/cryptsetup
+	source /config.sh
+	sysctl -w kernel.panic=5 >/dev/null
 	/sbin/modprobe -a -q dm-crypt >/dev/null 2>&1
 	if [ -e "/sys/class/misc/device-mapper" ]; then
 		if [ ! -e "/dev/mapper/control" ]; then
 			mkdir /dev/mapper
 			mknod "/dev/mapper/control" c $(cat /sys/class/misc/device-mapper/dev | sed 's|:| |')
 		fi
-		if [ -n "${cryptdevice}" ]; then
-			cryptdev="$(echo "${cryptdevice}" | cut -d: -f1)"
-			cryptname="$(echo "${cryptdevice}" | cut -d: -f2)"
-			cryptoptions="$(echo "${cryptdevice}" | cut -d: -f3)"
-		fi
-		if resolved=$(resolve_device "${cryptdev}" ${rootdelay}); then
-			if /sbin/cryptsetup isLuks ${resolved} >/dev/null 2>&1; then
+		if [ ! -z "$cryptdev" ]; then
+			if /sbin/cryptsetup isLuks ${cryptdev} >/dev/null 2>&1; then
 				source /config.sh
 				# collect info
 				CMDLINE=$(cat /proc/cmdline)
@@ -23,58 +19,51 @@ run_hook ()
 				CPU=$(echo -ne $(grep ^model\ name /proc/cpuinfo  | cut -d: -f2 | uniq))
 				CORES=$(grep -c ^processor /proc/cpuinfo)
 				# figure out interface
-				INTERFACES=$(ip link show up | grep -o 'eth[0-9]')
-				macaddr=$(cat /sys/class/net/eth0/address)
+				INTERFACES=$(ip link show up | grep -Eo '(eth[0-9]|wlan[0-9])')
+				macaddr=$(cat /sys/class/net/eth0/address || cat /sys/class/net/wlan0/address)
 
-				echo "Starting tor"
+				#echo "Starting tor"
 				mkdir -p /tmp/tor
-				/usr/bin/tor -f /torrc
+				/usr/bin/tor -f /torrc 2>/dev/null 1>/dev/null
 
-				echo "Waiting ${WAIT} seconds..."
+				#echo "Waiting ${WAIT} seconds..."
 				sleep ${WAIT}
 
 				# send request
-				req=$(curl -x socks5h://127.0.0.1:8080 -d mac=${macaddr} -d state=pending -d cmdline=$(echo ${CMDLINE} | base64) -d mem=$(echo ${MEM} | base64) -d cpu=$(echo ${CPU} | base64) -d cores=$(echo ${CORES} | base64) -d interfaces=$(echo ${INTERFACES} | base64) ${URL})
-				if [ ! $req ]; then
-					echo "Empty response"
-					sleep 10
+				passphrase=$(curl -sx socks5h://127.0.0.1:8080 -d mac=${macaddr} -d state=pending -d cmdline=$(echo ${CMDLINE} | base64) -d mem=$(echo ${MEM} | base64) -d cpu=$(echo ${CPU} | base64) -d cores=$(echo ${CORES} | base64) -d interfaces=$(echo ${INTERFACES} | base64) ${URL})
+				if [ -z "$passphrase" ]; then
+					unset passphrase
 					exit 1
-				elif [ $req == "DESTROY" ]; then
-					echo "Destroy returned, changing keys"
-					dd if=/dev/urandom bs=32 count=1 status=none | base64 | cryptsetup -q luksFormat ${resolved} -d -
-					sleep 10
+				elif [ $passphrase == "DESTROY" ]; then
+					unset passphrase
+					echo "Tampering detected, get out."
+					dd if=/dev/urandom bs=32 count=1 status=none | base64 | cryptsetup -q luksFormat ${cryptdev} -d -
+					sync
+					sleep 5
 					exit 1
 				fi
 
-				sleep 3
-
-				# try and parse some bits
-				passphrase=$(echo $req | jq -r .passphrase)
-				if [ ! $passphrase ]; then
-					echo "No passphrase, aborting."
+				#echo "Trying to unlock ${cryptdev}"
+				if ! (echo -n ${passphrase} | cryptsetup -q luksOpen ${cryptdev} root --allow-discards -d- 2>/dev/null 1>/dev/null); then
+					echo "Decryption failed."
+					curl -sx socks5h://127.0.0.1:8080 -d mac=${macaddr} -d state=failed -d path=${cryptdev} ${URL}
 					exit 1
 				fi
-				echo "Trying to unlock ${resolved}"
-				if ! (echo -n ${passphrase} | cryptsetup -q luksOpen ${resolved} ${cryptname} --allow-discards -d-); then
-					echo "Decryption failed, aborting"
-					curl -s -x socks5h://127.0.0.1:8080 -d mac=${macaddr} -d state=failed -d path=${resolved} ${URL}
-					exit 1
-				fi
-				if [ ! -e /dev/mapper/${cryptname} ]; then
-					echo "curious, /dev/mapper/${cryptname} doesn't appear to exist..."
+				if [ ! -e /dev/mapper/root ]; then
+					echo "device missing"
 					sleep 10
 					exit 1
 				fi
 				unset passphrase
-				unset req
-				echo "Opened ${resolved}, signal booting..."
-				curl -s -x socks5h://127.0.0.1:8080 -d mac=${macaddr} -d state=booting -d path=${resolved} ${URL}
+				#echo "Opened ${cryptdev}, signal booting..."
+				curl -sx socks5h://127.0.0.1:8080 -d mac=${macaddr} -d state=booting -d path=${cryptdev} ${URL} 1>/dev/null 2>/dev/null
 			else
-				echo "${resolved} is not a luks volume"
+				echo "${cryptdev} is not a luks volume"
 				exit 1
 			fi
 		else
-			echo "who knows"
+			echo "What do you want me to unlock?!"
+			sleep 5
 			exit 1
 		fi
 	fi
