Move java warning to install, spew but don't fail.

diff --git a/unifi-video.install b/unifi-video.install
--- a/unifi-video.install
+++ b/unifi-video.install
@@ -2,6 +2,10 @@ post_install() {
   systemd-sysusers unifi-video.conf
   chown -R unifi-video:unifi-video /usr/lib/unifi-video/
   ln -s $( which mongod) /usr/lib/unifi-video/bin/
+
+  if ! [[ -x $( which java ) ]]; then
+    echo "Could not find java, please use archlinux-java to select a default."
+  fi
 }
 
 # vim:set ts=2 sw=2 et:
