Bump version

diff --git a/updater.patch b/updater.patch
--- a/updater.patch
+++ b/updater.patch
@@ -1,73 +1,72 @@
 --- updater
 +++ updater
-@@ -110 +110 @@
--      while getopts ':abc:de:hilno:p:qrstuvy' opt; do
-+      while getopts ':abc:de:hilno:p:qrtvy' opt; do
-@@ -167,4 +166,0 @@
--          # TODO: remove '-s' in future version
--          s|u)
--            update='true'
--            ;;
-@@ -282 +277,0 @@
--  update='false'
-@@ -302 +297 @@
--  printf '%s' "${color_usage}Usage: ${0} [-abdhilnrsuvy] [-c CONFIG]"
-+  printf '%s' "${color_usage}Usage: ${0} [-abdhilnrvy] [-c CONFIG]"
-@@ -334 +328,0 @@
+@@ -119 +119 @@
+-			while getopts ':abc:de:g:hilno:p:qrstuvy' opt; do
++			while getopts ':abc:de:g:hilno:p:qrstvy' opt; do
+@@ -180,4 +179,0 @@
+-					# TODO: remove '-s' in future version
+-					s|u)
+-						update='true'
+-						;;
+@@ -297 +292,0 @@
+-	update='false'
+@@ -316 +311 @@
+-${color_usage}Usage: ${0} [-abdghilnrsuvy] [-c CONFIG] [-e VERSION] [-o OVERRIDE] [-p PROFILE]${no_color_stdout}
++${color_usage}Usage: ${0} [-abdghilnrvy] [-c CONFIG] [-e VERSION] [-o OVERRIDE] [-p PROFILE]${no_color_stdout}
+@@ -355 +349,0 @@
 -  -s          (Deprecated) This is an alias for -u .
-@@ -337 +330,0 @@
+@@ -358 +351,0 @@
 -  -u          Check for updates of this updater and install if available.
-@@ -480,51 +472,0 @@
+@@ -528,50 +520,0 @@
 -#    Update Updater     #
 -#########################
 -
--# update this updater
--# expects $@ as arguments
+-# Update this updater. Call this function with "$@" as argument.
 -update_updater() {
--  # update check has not been activated
--  [ "${update}" = 'false' ] && return 0
--  readonly new_updater="${tmp_dir}/new_updater"
--  if ! download_file "${new_updater}" \
--      'https://notabug.org/TotallyLeGIT/PH-userjs-updater/raw/main/updater'
--  then
--    print_warn 'Download of new updater failed'
--    return 1
--  fi
--  chmod u+x "${new_updater}"
--  current_updater_version="$("${script_path}" -v | cut -d ' ' -f 2)"
--  new_updater_version="$("${new_updater}" -v | cut -d ' ' -f 2)"
+-	# update check has not been activated
+-	[ "${update}" = 'false' ] && return 0
+-	readonly new_updater="${tmp_dir}/new_updater"
+-	if ! download_file "${new_updater}" \
+-			'https://notabug.org/TotallyLeGIT/PH-userjs-updater/raw/main/updater'
+-	then
+-		print_warn 'Download of new updater failed'
+-		return 1
+-	fi
+-	chmod u+x "${new_updater}"
+-	current_updater_version="$("${script_path}" -v | cut -d ' ' -f 2)"
+-	new_updater_version="$("${new_updater}" -v | cut -d ' ' -f 2)"
 -
--  # compare updater versions, if different
--  while [ "${current_updater_version}" != "${new_updater_version}" ]; do
--    difference="$((${new_updater_version%%.*}-${current_updater_version%%.*}))"
--    # newer version available
--    if [ "${difference}" -gt 0 ]; then
--      printv_info '0' 'updater' 'update available'
--      # apply update
--      if ! { cat "${new_updater}" > "${script_path}" ; } > /dev/null 2>&1; then
--        print_warn "No permission to write file: '${script_path}'"
--        return 1
--      fi
--      printv_info '1' 'changelog' \
--          'https://notabug.org/TotallyLeGIT/PH-userjs-updater/raw/main/CHANGELOG.md'
--      # update user.js with new version
--      "${script_path}" "${@}"
--      # exit with exit code from updater call above
--      exit "${?}"
--    # version number is equal (go to next number)
--    elif [ "${difference}" -eq 0 ]; then
--      current_updater_version="${current_updater_version#*.}"
--      new_updater_version="${new_updater_version#*.}"
--    # this should not be happening
--    else
--      print_warn 'Your updater version seems odd. Check updater homepage' \
--          'and/or update manually.'
--      return 2
--    fi
--  done
--  printv_info '0' 'updater' 'up to date'
+-	# compare updater versions, if different
+-	while [ "${current_updater_version}" != "${new_updater_version}" ]; do
+-		difference="$((${new_updater_version%%.*}-${current_updater_version%%.*}))"
+-		# newer version available
+-		if [ "${difference}" -gt 0 ]; then
+-			printv_info '0' 'updater' 'update available'
+-			# apply update
+-			if ! { cat "${new_updater}" > "${script_path}" ; } > /dev/null 2>&1; then
+-				print_warn "No permission to write file: '${script_path}'"
+-				return 1
+-			fi
+-			printv_info '1' 'changelog' \
+-					'https://notabug.org/TotallyLeGIT/PH-userjs-updater/raw/main/CHANGELOG.md'
+-			# update user.js with new version
+-			"${script_path}" "${@}"
+-			# exit with exit code from updater call above
+-			exit "${?}"
+-		# version number is equal (go to next number)
+-		elif [ "${difference}" -eq 0 ]; then
+-			current_updater_version="${current_updater_version#*.}"
+-			new_updater_version="${new_updater_version#*.}"
+-		# this should not be happening
+-		else
+-			print_warn 'Your updater version seems odd. Check updater homepage' \
+-					'and/or update manually.'
+-			return 2
+-		fi
+-	done
+-	printv_info '0' 'updater' 'up to date'
 -}
 -
 -#########################
-@@ -782 +723,0 @@
+@@ -851 +793,0 @@
 -update_updater "${@}"
