Tracking firefox-wayland-hg

diff --git a/upload-symbol-archive b/upload-symbol-archive
--- a/upload-symbol-archive
+++ b/upload-symbol-archive
@@ -1,8 +1,8 @@
 #!/bin/bash -e
 
 die() {
-    echo >&2 "$@"
-    exit 1
+  echo >&2 "$@"
+  exit 1
 }
 
 (( $# >= 2 )) || die "Usage: $0 TOKEN-FILE SYMBOL-ARCHIVE..."
@@ -12,14 +12,14 @@ shift
 [[ -f $token && -s $token ]] || die "Invalid TOKEN-FILE ${token@Q}"
 
 for zip; do
-    [[ $(file -Ebi "$zip") == application/zip* ]] || die "Invalid SYMBOL-ARCHIVE ${zip@Q}"
+  [[ $(file -Ebi "$zip") == application/zip* ]] || die "Invalid SYMBOL-ARCHIVE ${zip@Q}"
 done
 
 for zip; do
-    echo >&2 "Uploading ${zip@Q} ..."
-    curl -X POST -H "Auth-Token: $(<"$token")" -F "${zip##*/}=@$zip" \
-        --retry 4 --retry-connrefused --connect-timeout 120 \
-        https://symbols.mozilla.org/upload/
-    echo
-    mv -v "$zip" "$zip.uploaded"
+  echo >&2 "Uploading ${zip@Q} ..."
+  curl -X POST -H "Auth-Token: $(<"$token")" -F "${zip##*/}=@$zip" \
+    --retry 4 --retry-connrefused --connect-timeout 120 \
+    https://symbols.mozilla.org/upload/
+  echo
+  mv -v "$zip" "$zip.uploaded"
 done
