xash3d-git: updated

diff --git a/xash3d b/xash3d
--- a/xash3d
+++ b/xash3d
@@ -1,19 +1,19 @@
 #!/bin/sh
 . /etc/conf.d/xash3d
 
-DEFAULT_LIBPATH=/usr/lib32
+DEFAULT_LIBPATH=/usr/lib
 
 if [ ! -d "$XASH3D_BASEDIR" ]; then
-	echo "$XASH3D_BASEDIR not found"
-	exit 1
+    echo "$XASH3D_BASEDIR not found"
+    exit 1
 fi
 
-if [ ! -f "$XASH3D_BASEDIR/valve/dlls/hl.so" ]; then
-	if [ $(uname -m) != "x86_64" ]; then
-		DEFAULT_LIBPATH=/usr/lib
-	fi
-	ln -sr $DEFAULT_LIBPATH/valve/dlls/hl.so "$XASH3D_BASEDIR"/valve/dlls/hl.so
-	ln -sr $DEFAULT_LIBPATH/valve/cl_dlls/client.so "$XASH3D_BASEDIR"/valve/cl_dlls/client.so
+if [ $(uname -m) == "x86_64" ] && [ ! -f "$XASH3D_BASEDIR/valve/dlls/hl_amd64.so" ]; then
+    ln -sr $DEFAULT_LIBPATH/valve/dlls/hl_amd64.so "$XASH3D_BASEDIR"/valve/dlls/hl_amd64.so
+    ln -sr $DEFAULT_LIBPATH/valve/cl_dlls/client_amd64.so "$XASH3D_BASEDIR"/valve/cl_dlls/client_amd64.so
+elif [ ! -f "$XASH3D_BASEDIR/valve/dlls/hl.so" ]; then
+    ln -sr $DEFAULT_LIBPATH/valve/dlls/hl.so "$XASH3D_BASEDIR"/valve/dlls/hl.so
+    ln -sr $DEFAULT_LIBPATH/valve/cl_dlls/client.so "$XASH3D_BASEDIR"/valve/cl_dlls/client.so
 fi
 
 $DEFAULT_LIBPATH/xash3d/xash3d "$@"
