switching to symlink wrapper, minor cleanup, and updated maintainer
- package adopted and credited the previous maintainer baboon as a contributor
- now using a symbolic link to run /usr/bin/xenia_canary from ~/.xenia-canary
  instead of copying the binary
- improved the xenia-canary-bin wrapper script
- added post-install hook to inform users to run xenia-canary-bin
  (and NOT xenia_canary) directly if launching from the terminal
- clarified user data directory location in the post-install message
- updated sha512sums and set pkgver to 'latest' to avoid parsing errors
  and better handling with pamac (thx INeedTogepi)

diff --git a/xenia-canary-bin b/xenia-canary-bin
--- a/xenia-canary-bin
+++ b/xenia-canary-bin
@@ -1,29 +1,23 @@
 #!/bin/bash
 
-# bash wrapper that runs xenia_canary after copying it to $HOME/.xenia-canary
+# Wrapper that runs xenia_canary from ~/.xenia-canary using a symlink
 
-copybinary () {
-  cp -vf /usr/bin/xenia_canary $HOME/.xenia-canary/
-}
+set -e
 
-mkdir -p $HOME/.xenia-canary
-cd $HOME/.xenia-canary
+XENIA_DIR="$HOME/.xenia-canary"
+XENIA_BIN="$XENIA_DIR/xenia_canary"
+SYSTEM_BIN="/usr/bin/xenia_canary"
 
-if [ -f $HOME/.xenia-canary/xenia_canary ]; then
-  if command -v sha512sum &> /dev/null; then 
-    if [ $(sha512sum /usr/bin/xenia_canary | cut -d ' ' -f 1 ) != $(sha512sum $HOME/.xenia-canary/xenia_canary | cut -d ' ' -f 1 ) ]; then 
-      echo 'hash different between binary from /usr/bin and\$HOME/.xenia-canary'
-      copybinary
-    else
-      cp -vn /usr/bin/xenia_canary $HOME/.xenia-canary/
-    fi
-  else
-    echo 'no sha512sum command' 
-    cp -vi /usr/bin/xenia_canary $HOME/.xenia-canary/
-  fi
-else
-  echo '$HOME/.xenia-canary/xenia_canary does not exist'
-  copybinary
+mkdir -p "$XENIA_DIR"
+
+# Create or update the symlink
+if [ ! -L "$XENIA_BIN" ] || [ "$(readlink -- "$XENIA_BIN")" != "$SYSTEM_BIN" ]; then
+  ln -sfv "$SYSTEM_BIN" "$XENIA_BIN"
 fi
 
-exec $HOME/.xenia-canary/xenia_canary
+cd "$XENIA_DIR" || {
+  echo "Failed to cd into $XENIA_DIR" >&2
+  exit 1
+}
+
+exec "$XENIA_BIN"
